Repository LiskHQ/lisk-sdk, pull requests merged in 2018-09, with the labels that each got.

#2346 Add sort support to api/voters endpoint - Closes #2330
  db/sql/voters/get_voters.sql
  modules/voters.js
  schema/swagger.yml
  test/functional/http/get/voters.js
  test/unit/db/repos/voters.js
Labels: :eye: pending review

#2373 Poor performance of GET /api/delegates - Resolves #2351
  db/repos/accounts.js
  db/repos/rounds.js
  db/sql/index.js
  db/sql/migrations/updates/20180903001337_rename_rate_to_rank_in_delegates.sql
  db/sql/rounds/update_delegates_ranks.sql
  helpers/z_schema.js
  logic/account.js
  logic/round.js
  modules/delegates.js
  modules/transactions.js
  schema/swagger.yml
  test/fixtures/accounts.js
  test/functional/system/blocks/chain/delete_last_block_accounts.js
  test/functional/system/blocks/process/process_tables_data.json
  test/functional/system/rounds.js
  test/unit/common/sql/mem_accounts.js
  test/unit/db/repos/accounts.js
  test/unit/logic/account.js
  test/unit/logic/round.js
  test/unit/sql/mem_accounts_protection.js
Labels: :eye: pending review

#2344 Refactor checkIpInList function - Closes #2343, #2212
  helpers/check_ip_in_list.js
  helpers/http_api.js
  test/unit/helpers/check_ip_in_list.js
  test/unit/helpers/http_api.js
Labels: :white_check_mark: ready

#2376 Add sort support for username field on api/voters - Closes #2330
  modules/voters.js
  schema/swagger.yml
  test/functional/http/get/voters.js
Labels: :white_check_mark: ready

#2375 Better regular expression for verifying vote in verify vote - Close #627
  logic/vote.js
  test/functional/http/post/3.votes.js
  test/unit/logic/vote.js
Labels: :white_check_mark: ready

#2372 Remove duplicate asset rows from trs tables - Closes #2054
  db/sql/migrations/updates/20180829161959_remove_duplicate_rows_and_add_unique_constraint_in_dapps.sql
  db/sql/migrations/updates/20180829162051_remove_duplicate_rows_and_add_unique_constraint_in_votes.sql
  db/sql/migrations/updates/20180829162052_remove_duplicate_rows_and_add_unique_constraint_in_transfer.sql
  db/sql/migrations/updates/20180829162053_remove_duplicate_rows_and_add_unique_constraint_in_intransfer.sql
  db/sql/migrations/updates/20180830113940_remove_duplicate_rows_and_add_unique_constraint_in_multisignatures.sql
Labels: :white_check_mark: ready

#2378 Replace hardcoded values from description of Peer Disconnect network tests - Closes #2333
  test/network/index.js
  test/network/scenarios/p2p/peer_disconnect.js
  test/network/scenarios/p2p/peers_blacklist.js
Labels: :white_check_mark: ready

#2380 Disable totalAmount verification on Transaction - Closes #2319
  logic/transaction.js
  test/unit/logic/transaction.js
Labels: :white_check_mark: ready

#2379 Expire transaction test is failing randomly - Closes #2377
  test/integration/transactions/expire_transactions.js
Labels: :white_check_mark: ready

#2387 Use two different DNS domains for seed nodes - Closes #2347
  config/betanet/config.json
  config/mainnet/config.json
  config/testnet/config.json
Labels: :white_check_mark: ready

#2390 Update P2P layer connection logic so it can work with 1.0.0-rc.* releases - Closes #2389
  api/ws/rpc/connect.js
  helpers/patches.js
  modules/transport.js
  test/common/ws/client.js
  test/functional/ws/transport/client.js
  test/unit/api/ws/rpc/connect.js
  test/unit/helpers/patches.js
Labels: :white_check_mark: ready

#2393 Use jenkins nodes running nodejs 8 - Closes #1001
  Jenkinsfile
  Jenkinsfile.migration
  Jenkinsfile.network
  Jenkinsfile.nightly
  Jenkinsfile.nightly-build
  Jenkinsfile.private
Labels: :white_check_mark: ready

#2382 Use asynchronous childProcess commands in Network tests - Closes #2334
  Gruntfile.js
  test/network/scenarios/common.js
  test/network/scenarios/p2p/peer_disconnect.js
  test/network/scenarios/p2p/peers_blacklist.js
Labels: :white_check_mark: ready

#2397 Update P2P layer connection logic so it can work with 1.0.0-rc.* releases (development) - Closes #2389
  api/ws/rpc/connect.js
  helpers/patches.js
  modules/transport.js
  test/common/ws/client.js
  test/functional/ws/transport/client.js
  test/unit/api/ws/rpc/connect.js
  test/unit/helpers/patches.js
Labels: :white_check_mark: ready

#2395 Use jenkins nodes running nodejs 8 (development) - Closes #1001
  Jenkinsfile
  Jenkinsfile.migration
  Jenkinsfile.network
  Jenkinsfile.nightly
  Jenkinsfile.nightly-build
  Jenkinsfile.private
Labels: :white_check_mark: ready

#2392 Add tests to check Node & Postgresql versions - Closes #2388
  test/common/integration/sql/queriesHelper.js
  test/integration/dependencies.js
Labels: :white_check_mark: ready

#2405 Fixed README.md typos
  README.md
Labels: :white_check_mark: ready, good first contribution

#2396 API performance benchmarking via newrelic - Closes #1623, #1780
  README.md
  app.js
  helpers/newrelic_lisk.js
  newrelic.js
  package-lock.json
  package.json
  workers_controller.js
Labels: :white_check_mark: ready

#2401 Use proper name formatting for all SQL queries - Closes #2383
  db/repos/blocks.js
  db/repos/voters.js
  db/sql/blocks/get_common_block.sql
  db/sql/voters/get_voters.sql
  scripts/console.js
  test/unit/db/repos/blocks.js
Labels: :white_check_mark: ready

#2408 Fix inconsistent transactions response caused by senderIdOrRecipientId - Closes #2358
  modules/transactions.js
Labels: :white_check_mark: ready

#2402 Add support for running standalone tests - Closes #955
  .eslintrc.json
  Gruntfile.js
  test/common/parallel_tests.js
  test/functional/http/get/cache.js
  test/mocha.opts
Labels: :white_check_mark: ready

#2428 Fix merge mistake and update the rewire version
  package.json
Labels: :eye: pending review
