Repository LiskHQ/lisk-sdk, pull requests merged in 2018-04, with the labels that each got.

#1793 Update system headers and revert node network height changes - Closes #1778
  api/controllers/node.js
  modules/blocks/verify.js
  modules/node.js
  modules/peers.js
  modules/system.js
Labels: :eye: pending review

#1784 Add integration tests coverage for synchronize and broadcast modes - Closes #1751
  Jenkinsfile.nightly
  test/integration/transport.js
Labels: :eye: pending review

#1796 Improve jsdoc by replacing type {hash} with valid JavaScript type - Closes #1798
  helpers/ed.js
  logic/block.js
  logic/peer.js
  logic/transaction.js
Labels: :white_check_mark: ready

#1801 Fix chain recovery by changing getCommonBlock - Closes #1795
  db/repos/blocks.js
  db/sql/blocks/get_block_for_transport.sql
  db/sql/index.js
  modules/transport.js
  test/unit/db/repos/blocks.js
  test/unit/modules/transport.js
Labels: :eye: pending review

#1808 Update broadhash and height headers after block deletion - Closes #1803
  modules/blocks/chain.js
  modules/system.js
  test/unit/modules/blocks/chain.js
Labels: :eye: pending review

#1807 Database migrations must run in series but mutually exclusive to each other - Close #1806
  db/repos/migrations.js
  test/unit/db/repos/migrations.js
Labels: :eye: pending review

#1804 Migrations takes too long after rebuild from snapshot - Closes #1799
  db/sql/migrations/updates/20180205000003_create_rounds_rewards_table.sql
  db/sql/migrations/updates/20180205000004_apply_round_exception_mainnet.sql
Labels: :eye: pending review

#1810 Fix logs for peers listing attempt parameter - Closes #1809
  modules/peers.js
Labels: :eye: pending review

#1812 Sort delegates for nextForgers endpoint - Closes #1811
  modules/delegates.js
Labels: :eye: pending review

#1816 Sort delegates for nextForgers endpoint - Closes #1811
  modules/delegates.js
Labels: :eye: pending review

#1818 Block are not broadcasted properly - Closes #1817
  modules/blocks/chain.js
  modules/blocks/verify.js
  modules/loader.js
  modules/system.js
  modules/transport.js
  test/functional/system/blocks/chain/delete_last_block_db_trs.js
  test/unit/modules/blocks/chain.js
  test/unit/modules/blocks/verify.js
  test/unit/modules/transport.js
Labels: :eye: pending review

#1837 Sockets are not being cleaned up properly and are disconnecting too often - Closes #1836
  api/ws/rpc/connect.js
  test/unit/api/ws/rpc/connect.js
  workers_controller.js
Labels: :eye: pending review

#1842 Update lisk-js to beta - Closes #1828
  package.json
Labels: :white_check_mark: ready

#1854 Internal SocketCluster errors are not being logged - Closes #1853
  app.js
Labels: :white_check_mark: ready

#1863 Update wamp-socket-cluster to v1.0.0-beta.2
  package.json
Labels: :white_check_mark: ready

#1864 Log current socket number while connecting Peer - Closes #1859
  api/ws/rpc/connect.js
  test/unit/helpers/peers_manager.js
Labels: :white_check_mark: ready

#1860 Remove variable shadowing in transaction apply, applyUnconfirmed, undo, undoUnconfirmed - Closes #1726
  logic/delegate.js
  logic/in_transfer.js
  logic/multisignature.js
  logic/out_transfer.js
  logic/transaction.js
  logic/transfer.js
  logic/vote.js
Labels: :white_check_mark: ready

#1848 Add json schema validation for transaction.signatures property - Closes #1845
  logic/transaction.js
  schema/swagger.yml
  test/functional/http/post/4.multisignature.advanced.js
Labels: :white_check_mark: ready

#1857 Bump Node.js version to 6.14.1 - Closes #1844
  .nvmrc
  README.md
  package.json
Labels: :white_check_mark: ready

#1850 Extensive functionality for integration tests - Closes #1849
  Gruntfile.js
Labels: :eye: pending review

#1852 Reject transaction with requesterPublicKey - Closes #1847
  logic/transaction.js
  modules/transport.js
  test/functional/http/post/4.multisignature.advanced.js
  test/unit/logic/transaction.js
Labels: :eye: pending review

#1872 Tests negative verification result for manipulated data - Closes #1871
  test/unit/logic/block.js
Labels: :eye: pending review

#1888 Cannot debug worker processes for memory leaks - Closes #1887
  helpers/config.js
Labels: :white_check_mark: ready

#1874 Improve readability of verifySignature() - Closes #1873
  logic/block.js
Labels: :white_check_mark: ready

#1877 Never reuse sockets and always destroy socket instead of just disconnecting - Closes #1876
  api/ws/rpc/connect.js
  api/ws/rpc/disconnect.js
  test/unit/api/ws/rpc/disconnect.js
Labels: :stop_sign: failing

#1883 Node keeps on deleting blocks - Closes #1878
  db/sql/rounds/restore_round_snapshot.sql
  db/sql/rounds/restore_votes_snapshot.sql
  modules/blocks/chain.js
  test/functional/system/blocks/chain/delete_last_block_db_trs.js
  test/functional/system/rounds.js
  test/unit/modules/blocks/chain.js
Labels: :white_check_mark: ready

#1886 Terminate node on postgres connection error - Fixes #1779
  app.js
  db/index.js
Labels: :eye: pending review

#1897 Add code changes for handling inert transactions - Subtask #1880
  helpers/exceptions.js
  logic/transaction.js
  test/api/transactions.js
Labels: :eye: pending review

#1881 Inconsistent behavior between syncing and snapshotting - Closes #1879
  logic/transaction.js
  logic/transactionPool.js
  modules/blocks/process.js
  modules/blocks/verify.js
  modules/loader.js
  test/system/multisignature.js
  test/unit/logic/multisignature.js
  test/unit/logic/transaction.js
Labels: :eye: pending review

#1905 Add inert exceptions for testnet - Subtask #1880
  helpers/exceptions.js
Labels: :white_check_mark: ready

#1901 Truncate rounds_rewards table prior to start snapshotting - Closes #1900
  db/sql/accounts/reset_memory_tables.sql
  logic/account.js
Labels: :white_check_mark: ready

#1911 Upgrade socketcluster-client version - Closes #1908
  package.json
Labels: :white_check_mark: ready

#1815 Put transaction in right queue of transaction pool - Closes #1782
  logic/transaction_pool.js
  test/functional/system/rounds.js
  test/unit/logic/transaction_pool.js
Labels: :white_check_mark: ready

#1904 Remove blockId column from mem_acounts - Closes #1896
  db/repos/accounts.js
  db/repos/rounds.js
  db/sql/accounts/count_mem_accounts.sql
  db/sql/index.js
  db/sql/migrations/memory_tables.sql
  db/sql/migrations/updates/20180419001337_alter_mem_blockid_column.sql
  db/sql/rounds/insert_round_information_with_amount.sql
  db/sql/rounds/insert_round_information_with_delegate.sql
  db/sql/rounds/update_block_id.sql
  logic/account.js
  logic/in_transfer.js
  logic/multisignature.js
  logic/out_transfer.js
  logic/round.js
  logic/transaction.js
  logic/transfer.js
  logic/vote.js
  modules/loader.js
  modules/rounds.js
  test/fixtures/accounts.js
  test/fixtures/rounds.js
  test/functional/system/blocks/chain/delete_last_block_accounts.js
  test/functional/system/blocks/process/process_tables_data.json
  test/functional/system/rounds.js
  test/unit/common/sql/mem_accounts.js
  test/unit/db/repos/accounts.js
  test/unit/db/repos/rounds.js
  test/unit/logic/account.js
  test/unit/logic/in_transfer.js
  test/unit/logic/multisignature.js
  test/unit/logic/out_transfer.js
  test/unit/logic/round.js
  test/unit/modules/rounds.js
Labels: :eye: pending review

#1899 Use better socket timeouts - Closes #1898
  api/ws/rpc/connect.js
  api/ws/rpc/disconnect.js
  test/unit/api/ws/rpc/disconnect.js
  workers_controller.js
Labels: :white_check_mark: ready

#1912 Add P2P functional test for signatures - Closes #1697
  api/ws/rpc/connect.js
  api/ws/rpc/disconnect.js
  test/functional/http/post/4.multisignature.advanced.js
  test/integration/scenarios/index.js
  test/integration/scenarios/propagation/rpc/transactions/multisignature.js
  test/integration/transport.js
  workers_controller.js
Labels: :eye: pending review

#1917 Remove virgin column from mem_accounts - Closes #1895
  db/repos/accounts.js
  db/sql/accounts/convert_to_non_virgin.sql
  db/sql/index.js
  db/sql/migrations/memory_tables.sql
  db/sql/migrations/updates/20180423001337_remove_virgin_column.sql
  logic/account.js
  test/fixtures/accounts.js
  test/functional/system/app.js
  test/functional/system/blocks/chain/delete_last_block_accounts.js
  test/functional/system/blocks/process/process_tables_data.json
  test/functional/system/rounds.js
  test/functional/system/transactions/0.0.address_collision.js
  test/unit/common/sql/mem_accounts.js
  test/unit/db/repos/accounts.js
  test/unit/logic/account.js
  test/unit/logic/transaction.js
  test/unit/logic/transfer.js
  test/unit/modules/accounts.js
  test/unit/sql/mem_accounts_protection.js
Labels: :eye: pending review

#1829 Use authenticated passphrase encryption
  helpers/z_schema.js
  modules/delegates.js
  schema/config.js
  test/data/config.json
  test/data/genesis_delegates.json
  test/fixtures/accounts.js
  test/unit/logic/delegate.js
  test/unit/modules/delegates.js
Labels: :white_check_mark: ready

#1921 Extend version format to allow development QA - Closes #1918
  helpers/z_schema.js
  test/unit/helpers/z_schema.js
Labels: :eye: pending review

#1903 Add process monitoring and heap snapshotting
  app.js
  monitor.js
  package.json
Labels: :eye: pending review

#1924 Lint only relevant files prepush - Closes #1902
  package.json
Labels: :white_check_mark: ready

#1930 Node syncing with Peers below minVersion - Closes #1922
  logic/peers.js
  modules/peers.js
Labels: :white_check_mark: ready

#1929 Lint JS files in sql directories - Closes #1925
  .eslintignore
  db/sql/config.js
  db/sql/index.js
  test/functional/common/sql/queriesHelper.js
  test/unit/common/sql/mem_accounts.js
  test/unit/sql/mem_accounts_protection.js
Labels: :eye: pending review

#1939 Bump socketcluster-client version - Closes #1937
  package.json
Labels: :white_check_mark: ready

#1920 Provide API endpoint for transactions of an account - Closes #1892
  api/controllers/transactions.js
  modules/transactions.js
  schema/swagger.yml
  test/functional/http/get/transactions.js
Labels: :white_check_mark: ready

#1909 Reviving destroyed sockets memory leak - Closes #1907
  api/ws/rpc/connect.js
  api/ws/rpc/disconnect.js
  helpers/peers_manager.js
  test/unit/api/ws/rpc/connect.js
  test/unit/api/ws/rpc/disconnect.js
  test/unit/helpers/peers_manager.js
Labels: :white_check_mark: ready

#1944 Adjust the frequency of P2P discovery - Closes #1943
  modules/peers.js
  test/unit/modules/peers.js
Labels: :white_check_mark: ready

#1950 Set api get forges and votes limit to 101 - Closes #1800
  schema/swagger.yml
  test/functional/http/get/delegates.js
  test/functional/http/get/votes.js
Labels: :white_check_mark: ready

#1940 Rename "key" -> "password" for passphrase encryption - Closes #1923
  api/controllers/node.js
  modules/delegates.js
  modules/node.js
  schema/config.js
  schema/swagger.yml
  test/common/helpers/api.js
  test/common/utils/random.js
  test/data/config.json
  test/data/genesis_delegates.json
  test/fixtures/accounts.js
  test/functional/common/scenarios.js
  test/functional/http/get/accounts/accounts.js
  test/functional/http/get/dapps.js
  test/functional/http/get/delegates.js
  test/functional/http/get/node/transactions_unconfirmed.js
  test/functional/http/get/node/transactions_unprocessed.js
  test/functional/http/get/node/transactions_unsigned.js
  test/functional/http/get/transactions.js
  test/functional/http/get/voters.js
  test/functional/http/get/votes.js
  test/functional/http/post/0.transfer.js
  test/functional/http/post/1.second_secret.js
  test/functional/http/post/2.delegate.js
  test/functional/http/post/3.votes.js
  test/functional/http/post/5.dapps.js
  test/functional/http/post/6.dapps.in_transfer.js
  test/functional/http/post/7.dapps.out_transfer.js
  test/functional/http/post/common.js
  test/functional/http/put/node.js
  test/functional/system/blocks/chain/apply_block.js
  test/functional/system/blocks/chain/delete_last_block_accounts.js
  test/functional/system/blocks/chain/delete_last_block_db_trs.js
  test/functional/system/blocks/process/on_receive_block.js
  test/functional/system/get/transactions_unconfirmed.js
  test/functional/system/rounds.js
  test/functional/system/transactions/0.0.address_collision.js
  test/functional/system/transactions/0.0.transfer.js
  test/functional/system/transactions/1.second_signature/1.1.second_signature.js
  test/functional/system/transactions/1.second_signature/1.1.second_signature_from_pool_peer.js
  test/functional/system/transactions/1.second_signature/1.X.second_signature_unconfirmed.js
  test/functional/system/transactions/1.second_signature/1.X.second_signature_validated.js
  test/functional/system/transactions/2.delegates/1.same.account.same.username.js
  test/functional/system/transactions/2.delegates/2.same.account.different.usernames.js
  test/functional/system/transactions/2.delegates/3.different.accounts.same.username.js
  test/functional/system/transactions/2.delegates/4.different.accounts.different.usernames.js
  test/functional/system/transactions/2.delegates/5.same_account_from_pool_and_peer.js
  test/functional/system/transactions/3.3.votes.js
  test/functional/system/transactions/4.multisignature/4.multisignature_account.js
  test/functional/system/transactions/5.5.dapps.js
  test/integration/peers.integration.js
  test/integration/scenarios/stress/0.transfer.js
  test/integration/scenarios/stress/2.register_delegate.js
  test/integration/scenarios/stress/3.cast_vote.js
  test/integration/utils/http.js
  test/unit/logic/delegate.js
  test/unit/logic/multisignature.js
  test/unit/logic/transaction.js
  test/unit/logic/transfer.js
  test/unit/modules/cache.js
  test/unit/modules/node.js
Labels: :eye: pending review

#1926 Remove exceptions added in 0.9.13 for mainnet - Closes #1916
  helpers/exceptions.js
Labels: :white_check_mark: ready

#1951 Inconsistent IPv4 and IPv6 addresses - Closes #1947
  app.js
Labels: :white_check_mark: ready
