Repository LiskHQ/lisk-sdk, pull requests merged in 2018-05, with the labels that each got.

#1964 Update lisk-js to fixed latest version - Close #1961
  package.json
  test/common/utils/random.js
  test/functional/http/post/6.dapps.in_transfer.js
  test/functional/http/post/7.dapps.out_transfer.js
  test/functional/http/post/common.js
  test/functional/system/common.js
  test/functional/system/transactions/1.second_signature/1.X.second_signature_unconfirmed.js
  test/functional/system/transactions/1.second_signature/1.X.second_signature_validated.js
  test/functional/system/transactions/4.multisignature/4.X.multisignature_unconfirmed.js
  test/functional/system/transactions/4.multisignature/4.X.multisignature_validated.js
  test/integration/scenarios/propagation/rpc/transactions/multisignature.js
  test/integration/utils/transactions.js
Labels: :white_check_mark: ready

#1975 Update moment.js to 2.19.3 version - Closes #1974
  package.json
Labels: :white_check_mark: ready

#1960 CTRL+C on OSX throws error - Closes #1958
  app.js
Labels: :eye: pending review

#1987 Update functional system rounds tests to new behavior - Closes #1953
  test/functional/system/rounds.js
Labels: :white_check_mark: ready

#1948 Update integration tests to verify the open sockets on system level - Closes #1910
  test/integration/scenarios/network/peers.js
  test/integration/transport.js
  test/integration/utils/index.js
Labels: :eye: pending review

#1963 Refactor snapshotting mode - Closes #1949, #1927, #1869, #1868, #1933
  config.json
  db/repos/blocks.js
  db/repos/rounds.js
  db/sql/blocks/delete_blocks_after_height.sql
  db/sql/index.js
  helpers/config.js
  logic/round.js
  modules/loader.js
  modules/rounds.js
  schema/config.js
  test/data/config.json
  test/functional/system/snapshotting.js
  test/integration/configs/config.non-forge.json
  test/unit/db/repos/blocks.js
  test/unit/db/repos/rounds.js
  test/unit/logic/round.js
  test/unit/modules/loader.js
  test/unit/modules/loader.skeleton.js
  test/unit/modules/rounds.js
  test/unit/modules/transactions.js
Labels: :white_check_mark: ready

#1985 Make Access-Control-Allow-Origin header configurable - Closes #1973
  api/fittings/lisk_cors.js
  config.json
  config/swagger/default.yml
  helpers/config.js
  schema/config.js
  test/data/config.json
  test/unit/api/fittings/lisk_cors.js
Labels: :eye: pending review

#1983 Backport code changes for handling inert transactions - Closes #1981
  helpers/exceptions.js
  logic/transaction.js
Labels: :white_check_mark: ready

#1945 Wrong logic in transactions verify process - Closes #1928
  logic/transaction.js
  logic/transaction_pool.js
  modules/blocks/process.js
  modules/blocks/verify.js
  test/functional/http/post/transactions.js
  test/functional/system/transactions/1.second_signature/1.X.second_signature_validated.js
  test/functional/system/transactions/2.delegates/3.different.accounts.same.username.js
  test/functional/system/transactions/2.delegates/4.different.accounts.different.usernames.js
  test/functional/system/transactions/3.3.votes.js
  test/functional/system/transactions/4.multisignature/4.4.multisignature.js
  test/functional/system/transactions/4.multisignature/4.X.multisignature_validated.js
  test/functional/system/transactions/4.multisignature/4.multisignature_account.js
  test/unit/logic/transaction.js
  test/unit/logic/transaction_pool.js
  test/unit/modules/blocks/process.js
  test/unit/modules/blocks/verify.js
Labels: :white_check_mark: ready

#1952 Fix error occured on loading transport modules on application restart - Closes #1830
  app.js
Labels: :white_check_mark: ready

#1996 Change slack channel name in Jenkinsfile
  Jenkinsfile
Labels: :white_check_mark: ready, jenkins

#1971 Inconsistent response for /transactions endpoint - Closes #1884
  db/repos/transactions/index.js
  db/sql/migrations/updates/20180503114500_add_row_id_to_trs_list_view.sql
  test/functional/http/get/transactions.js
Labels: :white_check_mark: ready

#1989 Rename encryptedSecret -> encryptedPassphrase - Closes #1965
  helpers/z_schema.js
  modules/delegates.js
  schema/config.js
  test/data/config.json
  test/data/genesis_delegates.json
  test/fixtures/accounts.js
  test/unit/logic/delegate.js
  test/unit/modules/delegates.js
Labels: :eye: pending review

#1997 Backport inconsistent behavior between syncing and snapshotting - Closes #1976
  logic/transaction.js
  logic/transaction_pool.js
  modules/blocks/process.js
  modules/blocks/verify.js
  modules/loader.js
  test/functional/system/blocks/process/process.js
  test/functional/system/transactions/4.multisignature/4.multisignature_account.js
  test/unit/logic/transaction.js
  test/unit/logic/transaction_pool.js
  test/unit/modules/blocks/process.js
  test/unit/modules/blocks/verify.js
  test/unit/modules/loader.js
Labels: :eye: pending review

#2001 Inconsistent peers data from /api/peers - Closes #1955
  logic/peer.js
  test/integration/scenarios/network/peers.js
  test/unit/logic/peer.js
Labels: :white_check_mark: ready

#2006 Fix invalid broadhash consensus reported in logs - Closes #1832
  config.json
  modules/delegates.js
  modules/peers.js
  test/data/config.json
Labels: :white_check_mark: ready

#2007 Move istanbul-middleware to devDependencies - Close #1999
  .snyk
  app.js
  package.json
  test/common/utils/random.js
  test/functional/http/get/delegates.js
  test/functional/http/get/votes.js
  test/functional/http/post/6.dapps.in_transfer.js
  test/functional/http/post/7.dapps.out_transfer.js
  test/functional/system/blocks/process/on_receive_block.js
  test/functional/system/transactions/1.second_signature/1.X.second_signature_validated.js
  test/unit/db/repos/blocks.js
Labels: :eye: pending review

#1990 Write functional system tests for inert exceptions - Closes #1966
  test/functional/system/common.js
  test/functional/system/transactions/inert_transactions.js
Labels: :white_check_mark: ready

#2009 Next forgers endpoint returning invalid data - Closes #1998
  modules/delegates.js
Labels: :white_check_mark: ready

#2018 If a peer object for a specific nonce already exists and has a socket, destroy the socket - Closes #2012
  api/ws/rpc/disconnect.js
  helpers/peers_manager.js
  test/unit/api/ws/rpc/disconnect.js
Labels: :white_check_mark: ready

#2011 Remove unused code related to old http API - Closes #1986
  app.js
  config/swagger.js
  helpers/http_api.js
  helpers/router.js
  helpers/z_schema_express.js
  test/unit/helpers/http_api.js
  test/unit/helpers/z_schema_express.js
Labels: :white_check_mark: ready

#2023 Fix non-called callback - Closes #2021
  api/ws/rpc/connect.js
Labels: :white_check_mark: ready

#1968 Nightly builds - Closes #1936
  Jenkinsfile.nightly-build
Labels: :white_check_mark: ready

#2038 Block deletion outisde of SQL transaction - Closes #2036
  modules/blocks/chain.js
  test/unit/modules/blocks/chain.js
Labels: :eye: pending review

#2016 Review API documentation - Closes #1691
  schema/swagger.yml
Labels: :eye: pending review

#2043 Broadcast, FindGoodPeer and Broadcast header does not select intended peers - Closes #2042
  api/ws/rpc/connect.js
  logic/broadcaster.js
  logic/peers.js
  modules/loader.js
  modules/peers.js
  modules/transport.js
  test/unit/logic/broadcaster.js
  test/unit/logic/peers.js
  test/unit/modules/transport.js
Labels: :eye: pending review

#2050 Fix unreachable peers code of self-update - Closes #2029
  modules/peers.js
Labels: :white_check_mark: ready

#2052 Count peers after applying filter instead of total - Closes #2020
  api/controllers/peers.js
  modules/peers.js
  schema/swagger.yml
Labels: :white_check_mark: ready

#2065 Always select a non-lower peer to sync with
  modules/loader.js
Labels: :eye: pending review

#2017 Add integration test to cover Peer disconnects - Closes #2002
  test/common/ws/server_master.js
  test/integration/scenarios/index.js
  test/integration/scenarios/network/peer_disconnect.js
  test/integration/transport.js
  test/integration/utils/ws.js
Labels: :white_check_mark: ready

#2071 Add integration test to cover Peer disconnects - Fixes #2002
  test/integration/scenarios/network/peer_disconnect.js
  test/integration/transport.js
Labels: :eye: pending review
