Repository LiskHQ/lisk-sdk, pull requests merged in 2018-06, with the labels that each got.

#1938 Update Jenkins Migration to Use Lisk Bridge script to test migration - Closes #1861
  Jenkinsfile.migration
Labels: :white_check_mark: ready

#2085 Move and improve log messages for fork scenarios - Closes #2084
  modules/blocks/process.js
  test/unit/modules/blocks/process.js
Labels: :eye: pending review

#2090 Adjust configuration parameters for broadcasting - Closes #2077
  config.json
  test/data/config.json
Labels: :eye: pending review

#2093 Review functional system rounds tests and unskip tests - Closes #2092
  test/functional/system/rounds.js
Labels: :white_check_mark: ready

#2048 Add config.json migration script from from old version 0.9.x - Closes #2046
  .npmignore
  scripts/update_config.js
Labels: :building_construction: in progress

#2070 Nightly builds changes - Closes #2027
  Jenkinsfile.nightly-build
Labels: :stop_button: suspended, jenkins

#2056 Dockerfile with config.json templating - Closes #2053
  Dockerfile
  README.md
  docker_files/etc/confd/conf.d/lisk.toml
  docker_files/etc/confd/templates/config.json.tmpl
  docker_files/home/lisk/run.sh
  docker_files/home/lisk/wait-for-it.sh
Labels: :eye: pending review

#2104 Backport 0.9.15 changes to 1.0.0 - Closes #2097
  logic/transaction.js
  test/unit/logic/transaction.js
Labels: :white_check_mark: ready

#2105 Backport 0.9.16 changes to 1.0.0 - Closes #2098, #2102
  modules/blocks/chain.js
  test/functional/system/blocks/chain/apply_block.js
  test/unit/modules/blocks/chain.js
Labels: :eye: pending review

#2055 Remove rank parameter in delegates endpoint - Closes #1988
  api/controllers/delegates.js
  schema/swagger.yml
Labels: :white_check_mark: ready

#2106 During syncing, reject blocks received through broadcasts
  modules/blocks/process.js
  test/unit/modules/blocks/process.js
Labels: :white_check_mark: ready

#2060 Nightly tests failing on 1.0.0 branch - Closes #2022 #2094
  Jenkinsfile.nightly
  test/common/utils/wait_for.js
  test/integration/scenarios/common/stress.js
  test/integration/scenarios/index.js
  test/integration/scenarios/network/peer_disconnect.js
  test/integration/scenarios/stress/0.transfer.js
  test/integration/scenarios/stress/0.transfer_with_data.js.js
  test/integration/scenarios/stress/1.second_passphrase.js
  test/integration/scenarios/stress/2.register_delegate.js
  test/integration/scenarios/stress/3.cast_vote.js
  test/integration/scenarios/stress/4.register_multisignature.js
  test/integration/scenarios/stress/5.register_dapp.js
  test/integration/setup/network.js
  test/integration/setup/sync.js
  test/integration/transport.js
  test/integration/utils/ws.js
Labels: :white_check_mark: ready

#2095 Blacklist peers from config - Closes #2010
  api/ws/rpc/failure_codes.js
  api/ws/workers/middlewares/handshake.js
  app.js
  modules/peers.js
  test/integration/scenarios/index.js
  test/integration/scenarios/network/peers_blacklist.js
  test/integration/transport.js
  test/integration/utils/http.js
  test/unit/api/ws/middleware/handshake.js
  workers_controller.js
Labels: :white_check_mark: ready

#2108 Correct typo in config template - Closes #2107
  docker_files/etc/confd/templates/config.json.tmpl
Labels: :white_check_mark: ready

#2110 Improve Lisk Timestamps explanation - Closes #2109
  schema/swagger.yml
Labels: :eye: pending review

#2111 Allow client socket to behave as an RPC server
  api/ws/rpc/connect.js
  api/ws/rpc/ws_rpc.js
  test/unit/api/ws/rpc/connect.js
  test/unit/helpers/peers_manager.js
  test/unit/logic/peers.js
Labels: :building_construction: in progress

#2119 Make PUT /node/status/forging idempotent
  api/controllers/node.js
  modules/delegates.js
  modules/node.js
  package.json
  schema/swagger.yml
  test/common/swagger_spec.js
  test/functional/http/put/node.js
  test/integration/utils/http.js
  test/unit/modules/delegates.js
  test/unit/modules/node.js
Labels: :eye: pending review

#2113 Fix configuration template's forging section - Closes #2112
  README.md
  docker_files/etc/confd/templates/config.json.tmpl
Labels: :white_check_mark: ready

#2115 Configuration template for betanet
  docker_files/etc/confd/templates/config.json.tmpl
Labels: :white_check_mark: ready

#2124 beta8 does not sync from 0 because of invalid fee - Closes #2123
  helpers/exceptions.js
  logic/transaction.js
Labels: :white_check_mark: ready

#2127 Balances in mem_accounts off after snapshotting - Closes #2126
  db/sql/migrations/updates/20180205000003_create_rounds_rewards_table.sql
  modules/rounds.js
  test/functional/system/snapshotting.js
  test/unit/modules/rounds.js
Labels: :eye: pending review

#2131 Fix create_rounds_rewards_table SQL migration query - Fixes #2126
  db/sql/migrations/updates/20180205000003_create_rounds_rewards_table.sql
Labels: :white_check_mark: ready

#2137 Update configuration migration script to use correct wsPort for peers - Closes #2132
  scripts/update_config.js
Labels: :eye: pending review

#2142 Update script password for encryption minimum chars check - Closes #2141
  scripts/update_config.js
Labels: :white_check_mark: ready

#2143 Update script password for encryption minimum chars check - Closes #2141
  scripts/update_config.js
Labels: :white_check_mark: ready

#2144 Update script password for encryption minimum chars check - Closes #2141
  scripts/update_config.js
Labels: :white_check_mark: ready

#2150 Update milestone v1.0 - Closes #2145
  helpers/milestones.js
Labels: :eye: pending review

#2158 Update template for 1.0 testnet
  docker_files/etc/confd/templates/config.json.tmpl
Labels: :eye: pending review

#2162 Final readme review v1.0.0 (development) - Closes #2134
  README.md
Labels: :white_check_mark: ready

#2163 Update config script should allow password to be optional - Closes #2161
  scripts/update_config.js
Labels: :white_check_mark: ready

#2160 Blocks verify functional test is not covered in Jenkins parallel test - Closes #2151 #2152
  test/functional/system/blocks/verify/verify.js
Labels: :white_check_mark: ready

#2164 Final readme review v1.0.0 - Closes #2134
  README.md
Labels: :white_check_mark: ready

#2153 Change default delegate sorting to rank:asc - Closes #2138
  schema/swagger.yml
Labels: :white_check_mark: ready

#2171 forge should be called after fillPool and not before - Closes #2170
  modules/delegates.js
Labels: :white_check_mark: ready

#2169 Round fixes - Closes #216, #1783
  api/controllers/accounts.js
  api/controllers/delegates.js
  db/repos/accounts.js
  db/sql/rounds/perform_votes_snapshot.sql
  db/sql/rounds/restore_votes_snapshot.sql
  logic/account.js
  logic/round.js
  test/fixtures/accounts.js
  test/functional/system/blocks/chain/delete_last_block_accounts.js
  test/functional/system/rounds.js
  test/unit/db/repos/accounts.js
  test/unit/db/repos/rounds.js
  test/unit/logic/round.js
Labels: :eye: pending review

#2183 Update jenkins integration to use the dedicated build server - Closes #2182
  Jenkinsfile.integration
Labels: :white_check_mark: ready

#2177 Add sorting by producedBlocks - Closes #1716
  schema/swagger.yml
  test/functional/http/get/delegates.js
Labels: :white_check_mark: ready
