Repository LiskHQ/lisk-sdk, pull requests merged in 2018-07, with the labels that each got.

#2165 Send back better error when disconnecting because of invalid peer headers - Closes #2068
  api/ws/workers/middlewares/handshake.js
  test/functional/ws/transport/client.js
  test/unit/api/ws/middleware/handshake.js
Labels: :eye: pending review

#2174 Forging status broken after resync with beta7 - Closes #2058
  api/fittings/lisk_response_formatter.js
Labels: :white_check_mark: ready

#2176 Merge helpers/milestones.js to network specific exceptions - Closes #2155
  config/alphanet/exceptions.js
  config/betanet/exceptions.js
  config/devnet/exceptions.js
  config/mainnet/exceptions.js
  config/testnet/exceptions.js
  helpers/milestones.js
  logic/in_transfer.js
  logic/out_transfer.js
Labels: :white_check_mark: ready

#2193 Fix failing tests in Jenkins for 1.1.0 - Closes #2192
  config/devnet/config.json
  test/data/config.json
Labels: :white_check_mark: ready

#2181 Cleanup tests to use "devnet" configuration files to run all tests - Closes #2156
  Jenkinsfile
  Jenkinsfile.integration
  README.md
  config/alphanet/config.json
  config/betanet/config.json
  config/devnet/config.json
  config/mainnet/config.json
  config/testnet/config.json
  modules/system.js
  test/common/application.js
  test/common/modules_loader.js
  test/common/ws/client.js
  test/common/ws/server.js
  test/common/ws/server_master.js
  test/data/config.json
  test/data/genesis_block.json
  test/fixtures/blocks.js
  test/functional/http/get/node/node.js
  test/functional/http/get/transactions.js
  test/functional/system/blocks/chain/apply_block.js
  test/functional/system/blocks/chain/delete_last_block_db_trs.js
  test/functional/system/blocks/process/on_receive_block.js
  test/functional/system/blocks/process/process.js
  test/functional/system/blocks/verify/verify.js
  test/functional/system/transactions/1.second_signature/1.1.second_signature_from_pool_peer.js
  test/functional/system/transactions/2.delegates/5.same_account_from_pool_and_peer.js
  test/functional/ws/transport/blocks.js
  test/functional/ws/transport/client.js
  test/functional/ws/transport/handshake.js
  test/integration/peers.integration.js
  test/integration/transport.js
  test/setup.js
  test/unit/logic/round.js
  test/unit/modules/system.js
Labels: :white_check_mark: ready

#2196 Clean the version and minVersion config from all config files - Closes #2184
  Dockerfile
  config/alphanet/config.json
  config/betanet/config.json
  config/devnet/config.json
  config/mainnet/config.json
  config/testnet/config.json
  helpers/config.js
  package.json
  schema/config.js
  test/setup.js
Labels: :white_check_mark: ready

#2190 Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system - Closes #1835
  app.js
  config/alphanet/config.json
  config/betanet/config.json
  config/devnet/config.json
  config/mainnet/config.json
  config/testnet/config.json
  helpers/config.js
  schema/config.js
Labels: :eye: pending review

#2167 Different datatype for round number among different tables - Closes #1647
  db/sql/migrations/updates/20180626001337_change_round_type_in_mem_rounds.sql
  test/fixtures/rounds.js
  test/unit/db/repos/rounds.js
Labels: :eye: pending review

#2189 Improve vote transaction verification performance
  modules/delegates.js
  test/functional/http/post/3.votes.js
  test/unit/logic/vote.js
Labels: :white_check_mark: ready

#2200 Clean constants, exceptions and config files from all networks folders - Closes #2186
  README.md
  app.js
  config/alphanet/config.json
  config/alphanet/constants.js
  config/alphanet/exceptions.js
  config/betanet/config.json
  config/betanet/constants.js
  config/betanet/exceptions.js
  config/default/config.json
  config/default/constants.js
  config/default/exceptions.js
  config/devnet/config.json
  config/devnet/constants.js
  config/devnet/exceptions.js
  config/index.js
  config/mainnet/config.json
  config/mainnet/constants.js
  config/mainnet/exceptions.js
  config/swagger.js
  config/testnet/config.json
  config/testnet/constants.js
  config/testnet/exceptions.js
  helpers/config.js
  helpers/http_api.js
  scripts/generate_config.js
  test/common/application.js
  test/fixtures/types_representatives.js
  test/integration/scenarios/propagation/rpc/transactions/multisignature.js
  test/integration/scenarios/stress/0.transfer_with_data.js.js
  test/integration/scenarios/stress/1.second_passphrase.js
  test/integration/scenarios/stress/2.register_delegate.js
  test/integration/scenarios/stress/3.cast_vote.js
  test/integration/scenarios/stress/4.register_multisignature.js
  test/integration/scenarios/stress/5.register_dapp.js
  test/setup.js
  test/unit/helpers/z_schema.js
  test/unit/logic/block.js
  test/unit/logic/block_reward.js
  test/unit/logic/dapp.js
  test/unit/logic/in_transfer.js
  test/unit/logic/multisignature.js
  test/unit/logic/out_transfer.js
  test/unit/logic/signature.js
  test/unit/logic/transaction.js
  test/unit/logic/transfer.js
  test/unit/logic/vote.js
  test/unit/modules/loader.js
  test/unit/modules/peers.js
  test/unit/modules/transport.js
Labels: :white_check_mark: ready

#2197 SSL breaks Websocket connection - Closes #2154
  app.js
  config/default/config.json
  schema/config.js
  scripts/update_config.js
Labels: :building_construction: in progress

#2140 Replace libsodium wrapper - Closes #1797
  helpers/ed.js
  package.json
Labels: :white_check_mark: ready

#2223 Do not write defaultPassword to config when migrating - Closes #2208
  scripts/update_config.js
Labels: :white_check_mark: ready

#2224 SSL breaks Websocket connection - Closes #2154
  app.js
  config.json
  schema/config.js
  scripts/update_config.js
  test/data/config.json
Labels: :white_check_mark: ready

#2220 Change readme binaries to binary - Closes #2213
  README.md
Labels: :white_check_mark: ready

#2217 Fix config usage in worker_controller - Closes #2216
  workers_controller.js
Labels: :white_check_mark: ready

#2229 Set default db username during configuration migration - Closes #2227
  scripts/update_config.js
Labels: :eye: pending review

#2205 Update configuration migration script from 1.0.x to 1.1.x - Closes #2202
  package.json
  scripts/generate_config.js
  scripts/update_config.js
Labels: :eye: pending review

#2233 Add support for block versions - Closes #2199
  helpers/constants.js
  helpers/exceptions.js
  logic/block.js
  logic/block_version.js
  modules/blocks/verify.js
  test/functional/system/block_version.js
  test/functional/system/blocks/process/process.js
  test/functional/system/rounds.js
  test/functional/system/snapshotting.js
  test/unit/logic/block_version.js
  test/unit/modules/blocks/verify.js
Labels: :eye: pending review

#2228 NetworkHeight in /api/node/status is wrong - Closes #2179
  modules/peers.js
  test/unit/modules/peers.js
Labels: :white_check_mark: ready

#2235 Update to Node.js version 8.11.3 - Closes #2135
  .nvmrc
  README.md
  db/repos/blocks.js
  db/repos/peers.js
  db/repos/transactions/index.js
  db/repos/transactions/signature.js
  helpers/ed.js
  logic/account.js
  logic/block.js
  logic/multisignature.js
  logic/signature.js
  logic/transaction.js
  package-lock.json
  package.json
  test/functional/system/blocks/verify/verify.js
  test/functional/system/rounds.js
  test/unit/db/repos/blocks.js
  test/unit/db/repos/peers.js
  test/unit/db/repos/transactions/index.js
  test/unit/helpers/ed.js
  test/unit/logic/account.js
  test/unit/logic/block.js
  test/unit/logic/signature.js
  test/unit/logic/transaction.js
Labels: :white_check_mark: ready

#2242 Expectations are missing assertions - Closes #2236
  test/functional/system/blocks/verify/verify.js
  test/functional/system/rounds.js
  test/unit/logic/signature.js
  test/unit/logic/transfer.js
  test/unit/modules/transactions.js
Labels: :white_check_mark: ready

#2203 Review integration test suite - Close #2125
  Gruntfile.js
  Jenkinsfile
  Jenkinsfile.integration
  Jenkinsfile.nightly
  README.md
  tasks/mocha.js
  test/common/parallel_tests.js
  test/integration/index.js
  test/integration/integration.js
  test/integration/peers.integration.js
  test/integration/scenarios/common.js
  test/integration/scenarios/common/stress.js
  test/integration/scenarios/index.js
  test/integration/scenarios/network/peer_disconnect.js
  test/integration/scenarios/network/peers.js
  test/integration/scenarios/network/peers_blacklist.js
  test/integration/scenarios/propagation/blocks.js
  test/integration/scenarios/propagation/rpc/transactions/multisignature.js
  test/integration/scenarios/propagation/transactions.js
  test/integration/scenarios/stress/0.transfer_with_data.js.js
  test/integration/scenarios/stress/1.second_passphrase.js
  test/integration/scenarios/stress/2.register_delegate.js
  test/integration/scenarios/stress/3.cast_vote.js
  test/integration/scenarios/stress/4.register_multisignature.js
  test/integration/scenarios/stress/5.register_dapp.js
  test/integration/setup/config.js
  test/integration/setup/index.js
  test/integration/setup/network.js
  test/integration/setup/pm2.js
  test/integration/setup/shell.js
  test/integration/setup/sync.js
  test/integration/transport.js
  test/integration/utils/http.js
  test/integration/utils/index.js
  test/integration/utils/transactions.js
  test/integration/utils/ws.js
Labels: :white_check_mark: ready

#2241 Fix unstable unit test for vote - Closes #2207
  logic/account.js
  modules/delegates.js
  test/unit/logic/account.js
Labels: :white_check_mark: ready

#2232 Change the precedence of configurations to override custom configuration
  .gitignore
  README.md
  helpers/config.js
Labels: :white_check_mark: ready

#2244 Configuration migration of script rc2 should be compatible for rc1
  scripts/update_config.js
Labels: :white_check_mark: ready

#2234 Make docker images for 1.1 configurable - Closes #2180
  Dockerfile
  docker_files/etc/confd/templates/config.json.tmpl
  docker_files/home/lisk/run.sh
Labels: :white_check_mark: ready

#2195 Remove passing the scope of transaction logic to tx types - Closes #750
  logic/transaction.js
  logic/vote.js
  modules/accounts.js
  test/unit/logic/signature.js
  test/unit/logic/transfer.js
  test/unit/logic/vote.js
Labels: :white_check_mark: ready

#2251 Validate chain on startup of the application - Closes #2249
  helpers/slots.js
  modules/blocks/utils.js
  modules/loader.js
  test/functional/common/sql/queriesHelper.js
  test/functional/system/loader/validate_own_chain/first_round.js
  test/functional/system/loader/validate_own_chain/full_two_rounds.js
  test/functional/system/loader/validate_own_chain/more_than_two_rounds.js
Labels: :white_check_mark: ready

#2257 Add block version exception for devnet-rc2 branch - Closes #2258
  helpers/exceptions.js
  test/unit/modules/blocks/verify.js
Labels: :eye: pending review

#2250 Set db user in default config to 'lisk' - Closes #2248
  config/default/config.json
Labels: :white_check_mark: ready

#2253 Ban peers when validation of their blocks fails during sync - Closes #2252
  api/ws/rpc/failure_codes.js
  app.js
  helpers/ban_manager.js
  logic/peers.js
  modules/blocks/process.js
  test/common/application.js
  test/common/modules_loader.js
  test/unit/helpers/ban_manager.js
  test/unit/modules/blocks/process.js
Labels: :white_check_mark: ready

#2262 Refacor isValid function in logic/block_version - Closes #2199
  logic/block_version.js
  test/unit/logic/block_version.js
  test/unit/modules/blocks/verify.js
Labels: :eye: pending review

#2264 Add more logs and test to validate chain - Relates #2249
  modules/blocks/verify.js
  modules/loader.js
  test/functional/system/loader/validate_own_chain/valid_chain_full_round.js
  test/functional/system/loader/validate_own_chain/valid_chain_partial_round.js
Labels: :eye: pending review

#2267 Stringify Block to verify while logging - Relates #2249
  modules/loader.js
Labels: :white_check_mark: ready

#2268 Update load last block to follow the order of transactions in database - Relates #2249
  modules/blocks/utils.js
  test/unit/modules/blocks/utils.js
Labels: :white_check_mark: ready

#2270 Application should exit with status code 1 on any error in domain - Closes #2269
  app.js
Labels: :eye: pending review
