Repository LiskHQ/lisk-sdk, pull requests merged in 2019-01, with the labels that each got.

#2696 Update Peers Tests due to changes in Storage Sandbox - Closes #2694
  test/unit/storage/entities/peer.js
Labels: :eye: pending review

#2695 Remove db.peers repository - Closes #2631
  db/repos/index.js
  db/repos/peers.js
  db/sql/index.js
  db/sql/peers/clear.sql
  modules/peers.js
  storage/entities/peer.js
  storage/sql/peers/create.sql
  storage/sql/peers/delete.sql
  test/common/application.js
  test/unit/db/repos/peers.js
  test/unit/modules/peers.js
  test/unit/storage/entities/peer.js
Labels: :white_check_mark: ready

#2702 Allow sort to not force a default - Closes #2700
  storage/utils/sort_option.js
Labels: :white_check_mark: ready

#2690 Replace blocks getter interfaces with storage.entities.Block.get - Closes #2622
  logic/block.js
  modules/blocks.js
  modules/blocks/api.js
  modules/blocks/chain.js
  modules/blocks/process.js
  modules/blocks/utils.js
  modules/blocks/verify.js
  modules/loader.js
  modules/system.js
  modules/transport.js
  storage/entities/block.js
  storage/sql/blocks/get.sql
  storage/utils/inputSerializers.js
  test/integration/blocks/verify/verify.js
  test/unit/modules/blocks.js
  test/unit/modules/blocks/api.js
  test/unit/modules/blocks/chain.js
  test/unit/modules/blocks/process.js
  test/unit/modules/blocks/utils.js
  test/unit/modules/blocks/verify.js
  test/unit/modules/transport.js
  test/unit/storage/entities/block.js
Labels: :white_check_mark: ready

#2706 Use strict nodejs engine in docker
  Dockerfile
Labels: :white_check_mark: ready

#2693 Build: update Node.js GPG keyring - Closes #2689
  build/Makefile
  build/nodejs-keyring.gpg
Labels: :white_check_mark: ready

#2662 Create npm-shrinkwrap.json, use 'npm ci' in build - Closes #2656
  .gitignore
  Dockerfile
  README.md
  build/Makefile
  build/build.sh
  config/testnet/exceptions.js
  docker/.env.development
  docker/.env.mainnet
  docker/.env.testnet
  package-lock.json
  package.json
Labels: :white_check_mark: ready

#2711 Implement storage extended Block - Closes #2698
  storage/entities/block.js
  test/fixtures/storage/blocks.js
  test/unit/storage/entities/block.js
Labels: :white_check_mark: ready

#2714 Update Postgres version in README - Closes #2713
  README.md
Labels: :eye: pending review

#2716 Missing symlink of PM2 and Lisk Commander in builds - Closes #2715
  build/build.sh
Labels: :white_check_mark: ready

#2703 Replace transactions getter interfaces with storage.entities.Transaction.get - Closes #2621
  api/controllers/transactions.js
  db/repos/transactions/index.js
  db/sql/migrations/updates/20190104000001_add_recipient_public_key_to_full_block_list.sql
  helpers/newrelic_lisk.js
  modules/transactions.js
  storage/entities/base_entity.js
  storage/entities/transaction.js
  storage/sql/transactions/count.sql
  storage/sql/transactions/get.sql
  storage/sql/transactions/get_extended.sql
  test/integration/common.js
  test/unit/db/repos/blocks.js
  test/unit/db/repos/transactions/index.js
  test/unit/modules/transactions.js
  test/unit/storage/entities/transaction.js
Labels: :white_check_mark: ready

#2682 Add unit tests for signatures module - Closes #2445
  test/unit/modules/signatures.js
Labels: :eye: pending review

#2721 Remove unnecessary webSocket config parameter `appName` - Closes #2720
  app.js
  test/common/ws/server.js
  test/common/ws/server_process.js
Labels: :white_check_mark: ready

#2723 Update lisk-newrelic Node.js to v10.14.1 - Close #2722
  package.json
Labels: :eye: pending review

#2674 Disable multiple workers support on P2P layer - Closes #2541
  app.js
  config/default/config.json
Labels: :eye: pending review

#2727 Replace extended blocks getter interfaces with storage.entities.Block.get - Closes #2726
  logic/block.js
  logic/transaction.js
  modules/blocks/process.js
  modules/blocks/utils.js
  storage/entities/block.js
  storage/entities/transaction.js
  test/integration/blocks/process/process.js
  test/unit/modules/blocks/process.js
  test/unit/modules/blocks/utils.js
Labels: :white_check_mark: ready

#2725 Restore stability of peers blacklists and disconnections in Network Tests - Closes #2670
  Gruntfile.js
  test/network/index.js
  test/network/scenarios/p2p/peer_disconnect.js
  test/network/scenarios/p2p/peers.js
  test/network/scenarios/p2p/peers_blacklist.js
  test/network/scenarios/propagation/rpc/transactions/multisignature.js
  test/network/setup/config.js
Labels: :white_check_mark: ready

#2718 Use sodium-friends/sodium-native and bump to version 2.2.4 - Closes #2717
  package-lock.json
  package.json
Labels: :white_check_mark: ready

#2730 Refactor `modules.blocks[.shared]` namespace - Closes #2625
  api/controllers/blocks.js
  modules/blocks.js
  modules/blocks/api.js
  package.json
  test/unit/api/controllers/blocks.js
  test/unit/modules/blocks.js
Labels: :eye: pending review

#2740 Remove db.voters repository - Closes #2734
  db/repos/index.js
  db/repos/voters.js
  db/sql/index.js
  db/sql/voters/get_voters.sql
  db/sql/voters/get_voters_count.sql
  test/unit/db/repos/voters.js
Labels: :white_check_mark: ready

#2741 Remove db.votes repository - Closes #2733
  db/repos/index.js
  db/repos/votes.js
  db/sql/index.js
  db/sql/votes/get_votes.sql
  db/sql/votes/get_votes_count.sql
  test/unit/db/repos/votes.js
Labels: :white_check_mark: ready

#2742 Remove db.delegates repository - Closes #2735
  db/repos/delegates.js
  db/repos/index.js
  db/sql/delegates/insert_fork.sql
  db/sql/index.js
  modules/delegates.js
  modules/loader.js
  storage/entities/account.js
  storage/entities/round.js
  storage/sql/accounts/count_duplicated_delegates.sql
  storage/sql/accounts/insert_fork.sql
  test/fixtures/forks.js
  test/unit/db/repos/delegates.js
  test/unit/storage/entities/account.js
Labels: :white_check_mark: ready

#2750 getDelegatesFromPreviousRound using non existing library.db.rounds - Closes #2749
  modules/delegates.js
  storage/sql/rounds/get_delegates_snapshot.sql
  test/unit/storage/entities/round.js
Labels: :eye: pending review

#2738 Add interface to register entities with storage module - Closes #2736
  storage/errors.js
  storage/index.js
  storage/storage.js
  test/common/storage_sandbox.js
  test/unit/storage/storage.js
Labels: :eye: pending review

#2724 Remove db.transactions repository - Closes #2628
  api/controllers/dapps.js
  app.js
  db/repos/dapps.js
  db/repos/index.js
  db/repos/transactions/dapp.js
  db/repos/transactions/delegate.js
  db/repos/transactions/in_transfer.js
  db/repos/transactions/index.js
  db/repos/transactions/multisignature.js
  db/repos/transactions/out_transfer.js
  db/repos/transactions/signature.js
  db/repos/transactions/transfer.js
  db/repos/transactions/vote.js
  db/sql/dapps/count_by_out_transaction_id.sql
  db/sql/dapps/count_by_transaction_id.sql
  db/sql/dapps/get_existing.sql
  db/sql/dapps/get_genesis.sql
  db/sql/index.js
  db/sql/transactions/count.sql
  db/sql/transactions/count_by_id.sql
  db/sql/transactions/count_list.sql
  db/sql/transactions/get_dapp_by_ids.sql
  db/sql/transactions/get_delegate_by_ids.sql
  db/sql/transactions/get_in_transfer_by_ids.sql
  db/sql/transactions/get_multi_by_ids.sql
  db/sql/transactions/get_out_transfer_by_ids.sql
  db/sql/transactions/get_signature_by_ids.sql
  db/sql/transactions/get_transfer_by_ids.sql
  db/sql/transactions/get_votes_by_ids.sql
  logic/dapp.js
  logic/in_transfer.js
  logic/out_transfer.js
  logic/transaction.js
  modules/blocks/chain.js
  modules/dapps.js
  storage/entities/transaction.js
  test/common/application.js
  test/common/modules_loader.js
  test/unit/db/repos/dapps.js
  test/unit/db/repos/transactions/dapp.js
  test/unit/db/repos/transactions/delegate.js
  test/unit/db/repos/transactions/in_transfer.js
  test/unit/db/repos/transactions/index.js
  test/unit/db/repos/transactions/multisignature.js
  test/unit/db/repos/transactions/out_transfer.js
  test/unit/db/repos/transactions/signature.js
  test/unit/db/repos/transactions/transfer.js
  test/unit/db/repos/transactions/vote.js
  test/unit/logic/dapp.js
  test/unit/logic/in_transfer.js
  test/unit/logic/out_transfer.js
  test/unit/logic/transaction.js
  test/unit/modules/blocks/chain.js
  test/unit/storage/entities/transaction.js
Labels: :eye: pending review

#2755 Update node reference in Readme - Closes #2754
  README.md
Labels: :eye: pending review

#2739 Remove db.blocks repository - Closes #2629
  db/repos/blocks.js
  db/sql/blocks/block_exists.sql
  db/sql/blocks/count.sql
  db/sql/blocks/delete_after_block.sql
  db/sql/blocks/delete_block.sql
  db/sql/blocks/get_block_for_transport.sql
  db/sql/blocks/get_common_block.sql
  db/sql/blocks/get_genesis_block.sql
  db/sql/blocks/get_genesis_block_id.sql
  db/sql/blocks/get_height_by_last_id.sql
  db/sql/blocks/load_blocks_offset.sql
  db/sql/blocks/load_last_block.sql
  db/sql/blocks/load_last_n_block_ids.sql
  db/sql/index.js
  modules/blocks/chain.js
  modules/blocks/utils.js
  modules/loader.js
  storage/entities/account.js
  storage/entities/block.js
  storage/entities/transaction.js
  storage/sql/accounts/delegate_blocks_rewards.sql
  storage/sql/blocks/create.sql
  storage/sql/blocks/delete.sql
  storage/sql/blocks/get_first_block_id_of_last_rounds.sql
  test/functional/ws/transport/blocks.js
  test/unit/db/repos/blocks.js
  test/unit/modules/blocks.js
  test/unit/modules/blocks/chain.js
  test/unit/modules/blocks/utils.js
  test/unit/modules/delegates.js
  test/unit/modules/loader.js
  test/unit/storage/entities/account.js
  test/unit/storage/entities/block.js
Labels: :eye: pending review

#2757 Remove PM2 section from Readme - Closes #2756
  README.md
Labels: :eye: pending review, docs

#2792 Use lisk-scripts 0.7.0 - Closes #2791
  build/config.sh
Labels: :white_check_mark: ready

#2789 Fix JSDoc return type - Closes #2788
  storage/entities/base_entity.js
Labels: :white_check_mark: ready

#2785 Implement pending tests of DB Entities - Closes #2688
  storage/entities/account.js
  test/unit/storage/entities/account.js
  test/unit/storage/entities/block.js
  test/unit/storage/entities/migration.js
  test/unit/storage/entities/peer.js
  test/unit/storage/entities/transaction.js
Labels: :white_check_mark: ready

#2582 Refactor generateDelegateList & validateBlockSlot functions - Closes #2574, 2784
  modules/blocks/process.js
  modules/blocks/verify.js
  modules/delegates.js
  modules/rounds.js
  test/integration/app.js
  test/integration/blocks/process/on_receive_block.js
  test/integration/blocks/verify/verify.js
  test/integration/common.js
  test/integration/rounds.js
  test/unit/modules/blocks/process.js
  test/unit/modules/blocks/verify.js
  test/unit/modules/delegates.js
Labels: :eye: pending review

#2798 Hardcoded limit param to retrieve all the peers from storage - Closes #2787
  modules/peers.js
  test/unit/modules/peers.js
Labels: :white_check_mark: ready

#2786 Update cache module to be modified as component - Closes #2579 & #2802
  api/fittings/lisk_cache.js
  app.js
  components/cache/cache.js
  components/cache/constants.js
  components/cache/index.js
  helpers/newrelic_lisk.js
  helpers/redis_connector.js
  helpers/swagger_module_registry.js
  modules/accounts.js
  modules/blocks.js
  modules/blocks/chain.js
  modules/blocks/process.js
  modules/blocks/utils.js
  modules/blocks/verify.js
  modules/cache.js
  modules/dapps.js
  modules/delegates.js
  modules/loader.js
  modules/multisignatures.js
  modules/node.js
  modules/peers.js
  modules/rounds.js
  modules/signatures.js
  modules/system.js
  modules/transactions.js
  modules/transport.js
  storage/entities/block.js
  test/common/application.js
  test/common/modules_loader.js
  test/functional/http/get/cache.js
  test/functional/http/get/node/node.js
  test/integration/blocks/verify/verify.js
  test/network/scenarios/p2p/peer_protocol_version.js
  test/unit/api/ws/rpc/connect.js
  test/unit/components/cache.js
  test/unit/helpers/redis_connector.js
  test/unit/helpers/z_schema.js
  test/unit/logic/vote.js
  test/unit/modules/accounts.js
  test/unit/modules/blocks.js
  test/unit/modules/blocks/chain.js
  test/unit/modules/blocks/process.js
  test/unit/modules/blocks/utils.js
  test/unit/modules/blocks/verify.js
  test/unit/modules/cache.js
  test/unit/modules/loader.js
  test/unit/modules/multisignatures.js
  test/unit/modules/peers.js
  test/unit/modules/rounds.js
  test/unit/modules/signatures.js
  test/unit/modules/transactions.js
  test/unit/modules/transport.js
  test/unit/sql/mem_accounts_protection.js
  test/unit/storage/entities/base_entity.js
  test/unit/storage/entities/peer.js
Labels: :white_check_mark: ready

#2806 New migrations being created on wrong folder (old db folder) - Closes #2805
  tasks/new_migration.js
Labels: :white_check_mark: ready

#2811 Update logger to be modified as component - Closes #2578
  app.js
  framework/src/components/logger/index.js
  framework/src/components/logger/logger.js
  logger.js
  test/common/modules_loader.js
  test/framework/unit/components/cache.js
  test/functional/http/get/cache.js
  test/network/utils/index.js
  workers_controller.js
Labels: :eye: pending review
