Repository LiskHQ/lisk-sdk, pull requests merged in 2019-03, with the labels that each got.

#3010 Issue with account entity sql file - Close #3009
  framework/src/modules/chain/components/storage/entities/account.js
  framework/src/modules/chain/components/storage/sql/accounts/create_dependent_records.sql
Labels: :white_check_mark: ready

#2949 Update storage entity Transaction to contain just getters - Closes #2766
  framework/src/components/storage/entities/transaction.js
  framework/src/modules/chain/components/storage/entities/index.js
  framework/src/modules/chain/components/storage/entities/transaction.js
  framework/src/modules/chain/components/storage/sql/transactions/create.sql
  framework/src/modules/chain/init_steps/bootstrap_storage.js
  framework/test/mocha/common/storage_sandbox.js
  framework/test/mocha/unit/components/storage/entities/transaction.js
  framework/test/mocha/unit/modules/chain/components/storage/entitites/transaction.js
Labels: :eye: pending review

#2980 Remove numAmount z_schema and replace numbers genesis by strings - Closes #2957
  config/alphanet/genesis_block.json
  config/betanet/genesis_block.json
  config/devnet/genesis_block.json
  config/mainnet/genesis_block.json
  config/testnet/genesis_block.json
  framework/src/components/storage/entities/block.js
  framework/src/controller/schema/application.js
  framework/src/modules/chain/helpers/z_schema.js
Labels: :dizzy: quality assurance, :white_check_mark: ready

#3025 Remove applyUnconfirmedStep and undoUnconfirmedStep from the applyBlock and deleteLastBlock functions
  framework/src/modules/chain/modules/blocks/chain.js
  framework/test/mocha/integration/blocks/chain/apply_block.js
  framework/test/mocha/integration/blocks/chain/delete_last_block_accounts.js
  framework/test/mocha/integration/blocks/chain/delete_last_block_db_trs.js
  framework/test/mocha/unit/modules/chain/modules/blocks/chain.js
Labels: :white_check_mark: ready

#2970 Export storage component files through a root interface - Closes #2945
  framework/src/components/storage/adapters/index.js
  framework/src/components/storage/entities/account.js
  framework/src/components/storage/entities/base_entity.js
  framework/src/components/storage/entities/block.js
  framework/src/components/storage/entities/transaction.js
  framework/src/components/storage/index.js
  framework/src/components/storage/utils/field.js
  framework/src/components/storage/utils/filters.js
  framework/src/components/storage/utils/index.js
  framework/src/components/storage/utils/input_serializers.js
  framework/src/modules/chain/components/storage/entities/account.js
  framework/src/modules/chain/components/storage/entities/block.js
  framework/src/modules/chain/components/storage/entities/migration.js
  framework/src/modules/chain/components/storage/entities/peer.js
  framework/src/modules/chain/components/storage/entities/round.js
  framework/src/modules/chain/components/storage/entities/transaction.js
  framework/test/mocha/common/storage_sandbox.js
  framework/test/mocha/unit/components/storage/adapters/base_adapter.js
  framework/test/mocha/unit/components/storage/adapters/pgp_adapter.js
  framework/test/mocha/unit/components/storage/entities/account.js
  framework/test/mocha/unit/components/storage/entities/base_entity.js
  framework/test/mocha/unit/components/storage/entities/block.js
  framework/test/mocha/unit/components/storage/entities/transaction.js
  framework/test/mocha/unit/components/storage/utils/field.js
  framework/test/mocha/unit/components/storage/utils/filters.js
  framework/test/mocha/unit/components/storage/utils/inputSerializers.js
  framework/test/mocha/unit/modules/chain/components/storage/entitites/account.js
  framework/test/mocha/unit/modules/chain/components/storage/entitites/block.js
  framework/test/mocha/unit/modules/chain/components/storage/entitites/migration.js
  framework/test/mocha/unit/modules/chain/components/storage/entitites/peer.js
  framework/test/mocha/unit/modules/chain/components/storage/entitites/round.js
  framework/test/mocha/unit/modules/chain/components/storage/entitites/transaction.js
Labels: :white_check_mark: ready

#3028 Rename files to follow snake_case pattern - Closes #3012
  framework/src/modules/http_api/http_api.js
  framework/src/modules/http_api/index.js
  framework/test/mocha/common/integration/sql/queries_helper.js
  framework/test/mocha/integration/app.js
  framework/test/mocha/integration/block_version.js
  framework/test/mocha/integration/dependencies.js
  framework/test/mocha/integration/loader/validate_own_chain/first_round.js
  framework/test/mocha/integration/loader/validate_own_chain/full_two_rounds.js
  framework/test/mocha/integration/loader/validate_own_chain/more_than_two_rounds.js
  framework/test/mocha/integration/loader/validate_own_chain/valid_chain_full_round.js
  framework/test/mocha/integration/loader/validate_own_chain/valid_chain_partial_round.js
  framework/test/mocha/integration/rounds.js
  framework/test/mocha/integration/snapshotting.js
  framework/test/mocha/integration/transactions/0_0_transfer.js
  framework/test/mocha/integration/transactions/1_second_signature/1_1_second_signature.js
  framework/test/mocha/integration/transactions/1_second_signature/1_1_second_signature_from_pool_peer.js
  framework/test/mocha/integration/transactions/1_second_signature/1_X_second_signature_unconfirmed.js
  framework/test/mocha/integration/transactions/1_second_signature/1_X_second_signature_validated.js
  framework/test/mocha/integration/transactions/2_delegates/1_same_account_same_username.js
  framework/test/mocha/integration/transactions/2_delegates/2_same_account_different_usernames.js
  framework/test/mocha/integration/transactions/2_delegates/3_different_accounts_same_username.js
  framework/test/mocha/integration/transactions/2_delegates/4_different_accounts_different_usernames.js
  framework/test/mocha/integration/transactions/2_delegates/5_same_account_from_pool_and_peer.js
  framework/test/mocha/integration/transactions/3_3_votes.js
  framework/test/mocha/integration/transactions/3_votes_collision.js
  framework/test/mocha/integration/transactions/4_multisignature/4_4_multisignature.js
  framework/test/mocha/integration/transactions/4_multisignature/4_X_multisignature_edge_cases.js
  framework/test/mocha/integration/transactions/4_multisignature/4_X_multisignature_unconfirmed.js
  framework/test/mocha/integration/transactions/4_multisignature/4_X_multisignature_validated.js
  framework/test/mocha/integration/transactions/4_multisignature/4_multisignature_account.js
  framework/test/mocha/integration/transactions/4_multisignature/duplicate_signatures.js
  framework/test/mocha/integration/transactions/5_5_dapps.js
  framework/test/mocha/integration/transactions/expire_transactions.js
Labels: :eye: pending review

#2960 Refactor transaction validation in block normalization - Closes #2905
  framework/src/modules/chain/logic/block.js
  framework/src/modules/chain/modules/blocks.js
  framework/src/modules/chain/modules/blocks/verify.js
  framework/src/modules/chain/modules/loader.js
  framework/src/modules/chain/modules/process_transactions.js
  framework/src/modules/chain/modules/transport.js
  framework/test/mocha/integration/common.js
  framework/test/mocha/unit/modules/chain/logic/block.js
  framework/test/mocha/unit/modules/chain/modules/transport.js
Labels: :eye: pending review

#3015 Refactor undoing transactions and use the new StateStore and transactions library - Closes #3006
  framework/src/modules/chain/modules/blocks/chain.js
  framework/src/modules/chain/modules/process_transactions.js
  framework/test/mocha/integration/process_transactions.js
Labels: :eye: pending review

#3018 Remove storageRead call from http_api to chain - Closes #2989
  framework/src/modules/chain/chain.js
  framework/src/modules/chain/index.js
  framework/src/modules/chain/logic/block.js
  framework/src/modules/http_api/controllers/blocks.js
  framework/test/mocha/unit/modules/http_api/controllers/blocks.js
Labels: :white_check_mark: ready

#3031 Rename chain/modules/ folder to chain/submodules/ - Closes #3030
  framework/src/modules/chain/helpers/newrelic_lisk.js
  framework/src/modules/chain/init_steps/init_modules.js
  framework/src/modules/chain/submodules/accounts.js
  framework/src/modules/chain/submodules/blocks.js
  framework/src/modules/chain/submodules/blocks/chain.js
  framework/src/modules/chain/submodules/blocks/index.js
  framework/src/modules/chain/submodules/blocks/process.js
  framework/src/modules/chain/submodules/blocks/utils.js
  framework/src/modules/chain/submodules/blocks/verify.js
  framework/src/modules/chain/submodules/dapps.js
  framework/src/modules/chain/submodules/delegates.js
  framework/src/modules/chain/submodules/index.js
  framework/src/modules/chain/submodules/loader.js
  framework/src/modules/chain/submodules/multisignatures.js
  framework/src/modules/chain/submodules/peers.js
  framework/src/modules/chain/submodules/rounds.js
  framework/src/modules/chain/submodules/signatures.js
  framework/src/modules/chain/submodules/transactions.js
  framework/src/modules/chain/submodules/transport.js
  framework/test/mocha/common/application.js
  framework/test/mocha/common/modules_loader.js
  framework/test/mocha/integration/blocks/verify/verify.js
  framework/test/mocha/unit/modules/chain/helpers/jobs_queue.js
  framework/test/mocha/unit/modules/chain/submodules/accounts.js
  framework/test/mocha/unit/modules/chain/submodules/app.js
  framework/test/mocha/unit/modules/chain/submodules/blocks.js
  framework/test/mocha/unit/modules/chain/submodules/blocks/chain.js
  framework/test/mocha/unit/modules/chain/submodules/blocks/process.js
  framework/test/mocha/unit/modules/chain/submodules/blocks/utils.js
  framework/test/mocha/unit/modules/chain/submodules/blocks/verify.js
  framework/test/mocha/unit/modules/chain/submodules/dapps.js
  framework/test/mocha/unit/modules/chain/submodules/delegates.js
  framework/test/mocha/unit/modules/chain/submodules/loader.js
  framework/test/mocha/unit/modules/chain/submodules/loader.skeleton.js
  framework/test/mocha/unit/modules/chain/submodules/multisignatures.js
  framework/test/mocha/unit/modules/chain/submodules/peers.js
  framework/test/mocha/unit/modules/chain/submodules/rounds.js
  framework/test/mocha/unit/modules/chain/submodules/signatures.js
  framework/test/mocha/unit/modules/chain/submodules/transactions.js
  framework/test/mocha/unit/modules/chain/submodules/transport.js
Labels: :white_check_mark: ready

#3038 Block has no scope bind and transport validation is failing - Closes #3037
  framework/src/modules/chain/chain.js
  framework/src/modules/chain/modules/transport.js
  framework/test/mocha/common/application.js
Labels: :eye: pending review

#3019 Integrate @liskhq/lisk-p2p module in chain module - Closes #2874
  framework/src/components/system/system.js
  framework/src/controller/application.js
  framework/src/controller/schema/application.js
  framework/src/modules/chain/chain.js
  framework/src/modules/chain/index.js
  framework/src/modules/network/defaults/index.js
  framework/src/modules/network/index.js
  framework/src/modules/network/network.js
  framework/test/mocha/network/setup/config.js
  package-lock.json
  package.json
  src/index.js
Labels: :white_check_mark: ready

#3052 Fix coverage paths in Jenkinsfile - Closes #3051
  Jenkinsfile
Labels: :white_check_mark: ready

#3032 Add test coverage for moved api error codes - Closes #3021 #3029
  framework/src/modules/chain/chain.js
  framework/src/modules/http_api/controllers/delegates.js
  framework/src/modules/http_api/controllers/peers.js
  framework/src/modules/http_api/controllers/signatures.js
  framework/src/modules/http_api/controllers/transactions.js
  framework/src/modules/http_api/schema/swagger.yml
  framework/test/mocha/unit/modules/http_api/controllers/signatures.js
  framework/test/mocha/unit/modules/http_api/controllers/transactions.js
Labels: :white_check_mark: ready

#3048 Remove callbacks from chain module actions - Closes #2992, #3045
  framework/src/modules/chain/chain.js
  framework/src/modules/chain/helpers/newrelic_lisk.js
  framework/src/modules/chain/index.js
  framework/src/modules/chain/submodules/transactions.js
  framework/src/modules/http_api/controllers/node.js
  framework/test/mocha/integration/common.js
Labels: :white_check_mark: ready

#3043 Use src/index.js in Dockerfile and docker-compose.yml - Closes #3039
  Dockerfile
  docker/docker-compose.yml
Labels: :eye: pending review

#3044 Move "packaged" lisk-scripts - Closes #3042
  build/Makefile
  build/build.sh
  build/target/env.sh
  build/target/etc/pm2-lisk.json
  build/target/etc/pm2-snapshot.json
  build/target/etc/redis.conf
  build/target/etc/snapshot.json
  build/target/lisk.sh
  build/target/lisk_snapshot.sh
  build/target/shared.sh
  build/target/tune.sh
  build/target/var/db/blockchain.db.gz
Labels: :white_check_mark: ready

#3056 Remove symlinks from http api - Closes #3047
  framework/src/modules/chain/chain.js
  framework/src/modules/chain/helpers/z_schema.js
  framework/src/modules/chain/index.js
  framework/src/modules/http_api/controllers/blocks.js
  framework/src/modules/http_api/controllers/delegates.js
  framework/src/modules/http_api/controllers/node.js
  framework/src/modules/http_api/helpers/bignum.js
  framework/src/modules/http_api/helpers/slots.js
  framework/src/modules/http_api/helpers/transaction_types.js
  framework/src/modules/http_api/helpers/utils.js
  framework/src/modules/http_api/helpers/z_schema.js
  framework/test/mocha/functional/http/get/delegates.js
  framework/test/mocha/functional/http/get/voters.js
  framework/test/mocha/functional/http/get/votes.js
  framework/test/mocha/functional/http/post/0.transfer.js
  framework/test/mocha/functional/http/post/6.dapps.in_transfer.js
  framework/test/mocha/functional/http/post/7.dapps.out_transfer.js
  framework/test/mocha/unit/modules/http_api/controllers/delegates.js
Labels: :white_check_mark: ready

#3061 Drop `blocks_list` and `trs_list` views Closes - #2908
  framework/src/modules/chain/components/storage/sql/migrations/updates/20190313102300_drop_blocks_list_and_trs_list_views.sql
  framework/src/modules/chain/submodules/transactions.js
Labels: :white_check_mark: ready

#3064 Updating memberPublicKeys property for account does not work if the updated value is an empty array - Closes #3063
  framework/src/modules/chain/components/storage/entities/account.js
  framework/src/modules/chain/components/storage/sql/accounts/delete_all_dependent_records.sql
Labels: :white_check_mark: ready

#3049 Refactor transactions pool in lisk-core, and use transactions pool library - Closes #2829
  framework/src/modules/chain/logic/block.js
  framework/src/modules/chain/logic/state_store/transaction_store.js
  framework/src/modules/chain/logic/transaction.js
  framework/src/modules/chain/logic/transaction_pool.js
  framework/src/modules/chain/submodules/blocks/chain.js
  framework/src/modules/chain/submodules/blocks/process.js
  framework/src/modules/chain/submodules/blocks/verify.js
  framework/src/modules/chain/submodules/loader.js
  framework/src/modules/chain/submodules/multisignatures.js
  framework/src/modules/chain/submodules/process_transactions.js
  framework/src/modules/chain/submodules/transactions.js
  framework/src/modules/chain/submodules/transport.js
  framework/test/mocha/integration/blocks/chain/apply_block.js
  framework/test/mocha/integration/blocks/verify/verify.js
  framework/test/mocha/integration/common.js
  framework/test/mocha/integration/process_transactions.js
  framework/test/mocha/unit/modules/chain/logic/transaction_pool.js
  package-lock.json
  package.json
Labels: :white_check_mark: ready

#3065 Refactor chain actions with arguments - Closes #2991
  framework/src/modules/chain/chain.js
  framework/src/modules/http_api/controllers/accounts.js
  framework/src/modules/http_api/controllers/delegates.js
  framework/src/modules/http_api/controllers/node.js
  framework/src/modules/http_api/controllers/peers.js
  framework/src/modules/http_api/controllers/signatures.js
  framework/src/modules/http_api/controllers/transactions.js
  framework/test/mocha/functional/http/get/delegates.js
  framework/test/mocha/unit/modules/http_api/controllers/delegates.js
Labels: :white_check_mark: ready

#3050 Adapt scripts and configurations files to new structure - Closes 3041
  build/target/etc/pm2-lisk.json
  build/target/etc/pm2-snapshot.json
  build/target/lisk.sh
Labels: :white_check_mark: ready

#3069 Refactor channel.invoke to return only valid data - Closes #3068
  framework/src/modules/chain/chain.js
  framework/src/modules/chain/index.js
  framework/src/modules/http_api/controllers/delegates.js
  framework/src/modules/http_api/controllers/node.js
Labels: :eye: pending review

#2951 Add unit tests for controller codebase - Closes #2839
  framework/src/controller/bus.js
  framework/src/controller/channels/base.js
  framework/src/controller/channels/base/constants.js
  framework/src/controller/controller.js
  framework/src/controller/helpers/validator.js
  framework/test/jest/config/__mocks__/example.js
  framework/test/jest/config/unit/jest.config.js
  framework/test/jest/specs/unit/.gitkeep
  framework/test/jest/specs/unit/controller/action/action.spec.js
  framework/test/jest/specs/unit/controller/action/constants.js
  framework/test/jest/specs/unit/controller/application.spec.js
  framework/test/jest/specs/unit/controller/bus.spec.js
  framework/test/jest/specs/unit/controller/channels/base.spec.js
  framework/test/jest/specs/unit/controller/channels/base/__snapshots__/constants.spec.js.snap
  framework/test/jest/specs/unit/controller/channels/base/constants.spec.js
  framework/test/jest/specs/unit/controller/channels/event_emitter.spec.js
  framework/test/jest/specs/unit/controller/config/dirs.spec.js
  framework/test/jest/specs/unit/controller/controller.spec.js
  framework/test/jest/specs/unit/controller/defaults/__snapshots__/constants.spec.js.snap
  framework/test/jest/specs/unit/controller/defaults/constants.spec.js
  framework/test/jest/specs/unit/controller/event/constants.js
  framework/test/jest/specs/unit/controller/event/event.spec.js
  framework/test/jest/specs/unit/controller/helpers/validator.spec.js
  framework/test/jest/specs/unit/controller/schema/__snapshots__/application.spec.js.snap
  framework/test/jest/specs/unit/controller/schema/__snapshots__/config.spec.js.snap
  framework/test/jest/specs/unit/controller/schema/__snapshots__/constants.spec.js.snap
  framework/test/jest/specs/unit/controller/schema/application.spec.js
  framework/test/jest/specs/unit/controller/schema/config.spec.js
  framework/test/jest/specs/unit/controller/schema/constants.spec.js
  framework/test/jest/specs/unit/jest.config/__snapshots__/jest.config.unit.spec.js.snap
  framework/test/jest/specs/unit/jest.config/jest.config.unit.spec.js
Labels: :white_check_mark: ready

#3062 Update application readme - Closes #2974
  README.md
Labels: :white_check_mark: ready, docs

#3034 Update bus to support RPC connections and relevant channel should be introduced - Closes #3013
  framework/src/controller/application.js
  framework/src/controller/bus.js
  framework/src/controller/channels/base_channel.js
  framework/src/controller/channels/child_process_channel.js
  framework/src/controller/channels/in_memory_channel.js
  framework/src/controller/channels/index.js
  framework/src/controller/controller.js
  framework/src/modules/http_api/controllers/node.js
  framework/src/modules/http_api/index.js
  package-lock.json
  package.json
Labels: :white_check_mark: ready

#3082 Be more specific when checking whether PostgreSQL is running - Closes #3080
  build/target/lisk.sh
Labels: :white_check_mark: ready

#3083 Fix protocol version parsing with double digits - Closes #3081
  framework/src/components/system/system.js
  framework/test/mocha/unit/components/system/system.js
Labels: :white_check_mark: ready

#3091 Remove sequential tags from tests and Fix conflicting tests - Closes #3089
  framework/test/mocha/functional/http/get/cache.js
  framework/test/mocha/integration/transactions/expire_transactions.js
Labels: :white_check_mark: ready

#3078 Run mocha tests by npm scripts & Remove Gruntfile.js - Closes #2935
  .eslintrc.json
  .npmignore
  Gruntfile.js
  Jenkinsfile
  Jenkinsfile.extensive
  Jenkinsfile.network
  README.md
  framework/src/modules/chain/scripts/new_migration.js
  framework/src/modules/chain/tasks/.gitkeep
  framework/src/modules/chain/tasks/new_migration.js
  framework/test/mocha/common/lisk-mocha-runner/file_manager.js
  framework/test/mocha/common/lisk-mocha-runner/index.js
  framework/test/mocha/common/lisk-mocha-runner/process_manager.js
  framework/test/mocha/common/parallel_tests.js
  framework/test/mocha/functional/http/put/index.js
  package-lock.json
  package.json
Labels: :white_check_mark: ready

#3101 Functional test code coverage is broken - Closes #3100
  framework/src/modules/http_api/init_steps/setup_servers.js
Labels: :white_check_mark: ready

#3110 Makefile build - Closes #3099
  build/Makefile
  build/README.md
  build/build.sh
  build/config.sh
  build/darwin.mk
  build/target/var/db/blockchain.db.gz
Labels: :white_check_mark: ready

#3077 Wait for all sockets to be created on Bus and ChildProcessChannel - Closes #3073
  framework/src/controller/application.js
  framework/src/controller/bus.js
  framework/src/controller/channels/child_process_channel.js
  framework/src/controller/controller.js
  framework/src/modules/chain/chain.js
  framework/src/modules/chain/submodules/delegates.js
  framework/src/modules/http_api/http_api.js
  framework/test/mocha/unit/modules/chain/submodules/delegates.js
  src/index.js
Labels: :white_check_mark: ready

#3093 Add missing functional:put tests on Jenkins - Closes #3060
  Jenkinsfile
  README.md
  framework/test/mocha/common/lisk-mocha-runner/file_manager.js
  package.json
Labels: :white_check_mark: ready

#3094 Add jest tests to CI pipeline - Closes #2946
  Jenkinsfile
  framework/test/jest/config/jest.config.base.js
  framework/test/jest/specs/unit/controller/defaults/__snapshots__/constants.spec.js.snap
  framework/test/jest/specs/unit/controller/schema/__snapshots__/constants.spec.js.snap
  framework/test/jest/specs/unit/jest.config/__snapshots__/jest.config.unit.spec.js.snap
  package.json
Labels: :white_check_mark: ready

#3122 Fix Jenkinsfile for put tests - Closes #3121
  Jenkinsfile
Labels: :eye: pending review

#3120 Jenkins test is giving false positive - Closes #3113
  framework/test/mocha/common/lisk-mocha-runner/index.js
  framework/test/mocha/common/lisk-mocha-runner/process_manager.js
Labels: :white_check_mark: ready

#3057 Functional tests for validating asset field API - Closes #3053
  framework/test/mocha/functional/http/get/transactions.js
Labels: :white_check_mark: ready

#3116 Fix relative path -c option CLI
  README.md
  framework/src/modules/chain/helpers/config.js
Labels: :white_check_mark: ready

#3133 Fix failing network and core tests - Closes #3127
  framework/src/modules/chain/helpers/config.js
  framework/test/mocha/functional/http/get/transactions.js
  framework/test/mocha/functional/http/get/voters.js
  framework/test/mocha/network/setup/config.js
Labels: :white_check_mark: ready

#3137 Pipeline options are empty on the first run on Jenkins - Closes #3136
  Jenkinsfile
Labels: :eye: pending review

#3108 Fix votes calculated for delegates in round - Closes #3107
  framework/src/modules/chain/components/storage/entities/account.js
  framework/src/modules/chain/logic/rounds_information.js
  framework/src/modules/chain/logic/state_store/index.js
  framework/src/modules/chain/logic/state_store/round_store.js
  framework/src/modules/chain/logic/transaction.js
  framework/src/modules/chain/logic/transaction_pool.js
  framework/src/modules/chain/submodules/blocks/chain.js
  framework/src/modules/chain/submodules/process_transactions.js
  framework/src/modules/chain/submodules/rounds.js
  framework/test/mocha/integration/rounds.js
  framework/test/mocha/integration/state_store/round_store.js
  framework/test/mocha/unit/modules/chain/logic/rounds_information.js
  framework/test/mocha/unit/modules/chain/logic/transaction_pool.js
  framework/test/mocha/unit/modules/chain/submodules/rounds.js
Labels: :eye: pending review

#3148 Update packages versions - Closes #3147
  package-lock.json
  package.json
Labels: :eye: pending review

#3135 Fix missing log file and apply logging level - Closes #3123
  framework/src/components/logger/logger.js
  framework/src/controller/schema/application.js
  framework/src/modules/chain/helpers/config.js
  framework/test/jest/specs/unit/controller/schema/__snapshots__/application.spec.js.snap
  src/index.js
Labels: :white_check_mark: ready

#3126 Remove insecure chain actions - Closes #3033
  framework/src/modules/chain/chain.js
  framework/src/modules/chain/index.js
  framework/src/modules/http_api/controllers/node.js
  framework/test/mocha/functional/http/get/voters.js
  framework/test/mocha/unit/modules/http_api/controllers/delegates.js
Labels: :white_check_mark: ready

#3128 Implemment once() for ChildProcessChannel subSocket - Closes #3102
  framework/src/controller/channels/child_process_channel.js
Labels: :white_check_mark: ready

#3155 Error objects not being correctly logged - Closes #3092
  src/index.js
Labels: :eye: pending review

#3125 Upgrade Node.js version from 10.14.1 to 10.15.3 - Closes #3124
  .nvmrc
  README.md
  build/nodejs-keyring.gpg
  package.json
Labels: :white_check_mark: ready

#3114 lisk_snapshot.sh: dump directly from database - Closes #3109
  build/target/lisk_snapshot.sh
Labels: :white_check_mark: ready

#3132 Fix brittle cache tests - Closes #3131
  framework/src/components/cache/cache.js
  framework/test/mocha/unit/components/cache/cache.js
Labels: :white_check_mark: ready

#3103 Load http_api module as a child process - Closes #3059
  config/default/config.json
  config/devnet/config.json
  framework/src/controller/application.js
  framework/src/controller/bus.js
  framework/src/controller/channels/child_process_channel.js
  framework/src/controller/child_process_loader.js
  framework/src/controller/controller.js
  framework/src/controller/helpers/validator.js
  framework/src/controller/schema/application.js
  framework/src/modules/chain/submodules/delegates.js
  framework/test/jest/specs/unit/controller/bus.spec.js
  framework/test/jest/specs/unit/controller/channels/in_memory_channel.spec.js
  framework/test/jest/specs/unit/controller/controller.spec.js
  framework/test/jest/specs/unit/controller/schema/__snapshots__/application.spec.js.snap
  framework/test/mocha/unit/modules/chain/submodules/delegates.js
  src/index.js
Labels: :eye: pending review

#3105 Validate filter getter methods - Closes #3005
  framework/src/components/storage/entities/account.js
  framework/src/components/storage/entities/base_entity.js
  framework/src/components/storage/entities/transaction.js
  framework/src/modules/http_api/controllers/accounts.js
  framework/src/modules/http_api/controllers/blocks.js
  framework/src/modules/http_api/controllers/dapps.js
  framework/src/modules/http_api/controllers/delegates.js
  framework/src/modules/http_api/controllers/node.js
  framework/src/modules/http_api/controllers/peers.js
  framework/src/modules/http_api/controllers/voters.js
  framework/test/mocha/functional/http/get/blocks.js
  framework/test/mocha/functional/http/get/dapps.js
  framework/test/mocha/functional/http/get/delegates.js
  framework/test/mocha/functional/http/get/peers.js
  framework/test/mocha/functional/http/get/transactions.js
  framework/test/mocha/functional/http/get/voters.js
  framework/test/mocha/functional/http/get/votes.js
  framework/test/mocha/unit/components/storage/entities/account.js
  framework/test/mocha/unit/components/storage/entities/base_entity.js
  framework/test/mocha/unit/components/storage/entities/transaction.js
  framework/test/mocha/unit/modules/chain/logic/account.js
Labels: :white_check_mark: ready

#3167 Event & Action name validation regex definitions are different in Base class - Closes #3008
  framework/src/controller/channels/base.js
  framework/src/controller/channels/base/constants.js
  framework/src/controller/event.js
Labels: :white_check_mark: ready

#3165 Implement pending unit tests http api module - Closes #2988
  framework/src/modules/http_api/init_steps/bootstrap_cache.js
  framework/src/modules/http_api/init_steps/bootstrap_storage.js
  framework/src/modules/http_api/init_steps/bootstrap_swagger.js
  framework/src/modules/http_api/init_steps/index.js
  framework/src/modules/http_api/init_steps/setup_servers.js
  framework/src/modules/http_api/init_steps/start_listening.js
  framework/src/modules/http_api/init_steps/subscribe_to_events.js
  framework/test/mocha/unit/modules/chain/logic/round.js
  framework/test/mocha/unit/modules/http_api/http_api.js
  framework/test/mocha/unit/modules/http_api/init_steps/bootstrap_cache.js
  framework/test/mocha/unit/modules/http_api/init_steps/bootstrap_storage.js
  framework/test/mocha/unit/modules/http_api/init_steps/bootstrap_swagger.js
  framework/test/mocha/unit/modules/http_api/init_steps/setup_servers.js
  framework/test/mocha/unit/modules/http_api/init_steps/start_listening.js
  framework/test/mocha/unit/modules/http_api/init_steps/subscribe_to_events.js
Labels: :white_check_mark: ready

#3179 Remove jest-chain - Closes #3177
  framework/test/jest/config/setup.js
  framework/test/jest/specs/unit/controller/controller.spec.js
  package-lock.json
  package.json
Labels: :eye: pending review

#3168 Prevent application from crashing if child process crashes - Closes #3142
  framework/src/controller/bus.js
  framework/src/controller/channels/child_process_channel.js
  framework/src/controller/controller.js
  framework/src/modules/chain/index.js
  framework/src/modules/http_api/index.js
  framework/test/jest/specs/unit/controller/bus.spec.js
  package-lock.json
  package.json
Labels: :eye: pending review

#3184 Lisk Core should start without Redis - Closes #3176
  framework/src/components/cache/cache.js
Labels: :white_check_mark: ready

#3129 Update README file to reflect the modular architecture changes - Closes #3075
  README.md
  framework/src/components/README.md
  framework/src/controller/README.md
  framework/src/modules/README.md
Labels: :eye: pending review

#3170 Implement unit tests for ChildProcessChannel - Closes #3117
  framework/src/controller/channels/child_process/index.js
  framework/src/controller/channels/child_process_channel.js
  framework/src/controller/helpers/validator.js
  framework/test/jest/config/setup.js
  framework/test/jest/specs/unit/__mocks__/pm2-axon.js
  framework/test/jest/specs/unit/controller/channels/child_process/index.spec.js
  framework/test/jest/specs/unit/controller/channels/child_process_channel.spec.js
  framework/test/jest/specs/unit/controller/channels/in_memory_channel.spec.js
  framework/test/jest/specs/unit/controller/controller.spec.js
Labels: :eye: pending review

#3169 Fix Unit Tests - Closes #3134
  framework/test/mocha/fixtures/accounts.js
  framework/test/mocha/unit/components/storage/entities/account.js
  framework/test/mocha/unit/modules/chain/common/sql/mem_accounts.js
  framework/test/mocha/unit/modules/chain/components/storage/entitites/account.js
  framework/test/mocha/unit/modules/chain/logic/account.js
  framework/test/mocha/unit/modules/chain/logic/block.js
  framework/test/mocha/unit/modules/chain/logic/broadcaster.js
  framework/test/mocha/unit/modules/chain/logic/round.js
  framework/test/mocha/unit/modules/chain/sql/mem_accounts_protection.js
  framework/test/mocha/unit/modules/chain/submodules/blocks/chain.js
  framework/test/mocha/unit/modules/chain/submodules/blocks/process.js
  framework/test/mocha/unit/modules/chain/submodules/blocks/utils.js
  framework/test/mocha/unit/modules/chain/submodules/blocks/verify.js
  framework/test/mocha/unit/modules/chain/submodules/multisignatures.js
  framework/test/mocha/unit/modules/chain/submodules/signatures.js
  framework/test/mocha/unit/modules/chain/submodules/transactions.js
  framework/test/mocha/unit/modules/chain/submodules/transport.js
Labels: :eye: pending review

#3192 Revert child process auto-reload - Closes #3191
  framework/src/controller/bus.js
  framework/src/controller/controller.js
  framework/src/modules/chain/index.js
  framework/src/modules/http_api/index.js
Labels: :eye: pending review

#3186 Integration test for InMemoryChannel - Partially Closes #3118
  framework/test/jest/config/integration/jest.config.js
  framework/test/jest/specs/integration/.gitkeep
  framework/test/jest/specs/integration/in_memory_channel.spec.js
  package-lock.json
  package.json
Labels: :white_check_mark: ready

#3166 Fix integration test for transactions in branch: feature/improve_transactions_processing_efficiency - Closes #3143
  framework/src/modules/chain/logic/transaction_pool.js
  framework/src/modules/chain/submodules/blocks/chain.js
  framework/src/modules/chain/submodules/blocks/verify.js
  framework/src/modules/chain/submodules/process_transactions.js
  framework/test/mocha/integration/transactions/0.0.address_collision.js
  framework/test/mocha/integration/transactions/1_second_signature/1_1_second_signature.js
  framework/test/mocha/integration/transactions/1_second_signature/1_1_second_signature_from_pool_peer.js
  framework/test/mocha/integration/transactions/2_delegates/1_same_account_same_username.js
  framework/test/mocha/integration/transactions/2_delegates/2_same_account_different_usernames.js
  framework/test/mocha/integration/transactions/2_delegates/3_different_accounts_same_username.js
  framework/test/mocha/integration/transactions/2_delegates/4_different_accounts_different_usernames.js
  framework/test/mocha/integration/transactions/2_delegates/5_same_account_from_pool_and_peer.js
  framework/test/mocha/integration/transactions/3_3_votes.js
  framework/test/mocha/integration/transactions/4_multisignature/4_4_multisignature.js
  framework/test/mocha/integration/transactions/4_multisignature/4_X_multisignature_edge_cases.js
  framework/test/mocha/integration/transactions/4_multisignature/4_X_multisignature_validated.js
  framework/test/mocha/integration/transactions/4_multisignature/4_multisignature_account.js
  framework/test/mocha/integration/transactions/5_5_dapps.js
  framework/test/mocha/integration/transactions/expire_transactions.js
  framework/test/mocha/integration/transactions/inert_transactions.js
Labels: :white_check_mark: ready

#3207 Fix typo in newrelic lisk - Closes #3206
  framework/src/modules/chain/helpers/newrelic_lisk.js
Labels: :white_check_mark: ready

#3202 Build failed with errors - Closes #3199
  framework/src/modules/http_api/init_steps/setup_servers.js
Labels: :white_check_mark: ready

#3205 Newrelic throws error on start - Closes #3200
  package-lock.json
  package.json
Labels: :white_check_mark: ready

#3130 Process incoming signatures using statestore and elements - Closes #2825
  framework/src/modules/chain/chain.js
  framework/src/modules/chain/submodules/multisignatures.js
  framework/src/modules/chain/submodules/process_transactions.js
  framework/src/modules/chain/submodules/transport.js
  framework/test/mocha/integration/transactions/4_multisignature/duplicate_signatures.js
  framework/test/mocha/unit/modules/chain/submodules/multisignatures.js
  framework/test/mocha/unit/modules/chain/submodules/transport.js
Labels: :eye: pending review

#3211 Exit event does not kill all the processes - Closes #3201
  framework/src/controller/child_process_loader.js
Labels: :white_check_mark: ready

#3218 Lisk Node failed to start with snapshot mode - Closes #3214
  framework/src/modules/chain/chain.js
  framework/src/modules/chain/init_steps/create_socket_cluster.js
Labels: :eye: pending review

#3219 Fix broadhash http api - Closes #3217
  framework/src/modules/chain/chain.js
  framework/src/modules/chain/index.js
  framework/src/modules/http_api/controllers/node.js
  framework/src/modules/http_api/http_api.js
  framework/test/mocha/unit/modules/http_api/controllers/node.js
  framework/test/mocha/unit/modules/http_api/http_api.js
Labels: :white_check_mark: ready

#3220 PM2 does not show CPU and Memory usage as expected - Closes #3215
  build/target/etc/pm2-lisk.json
  build/target/etc/pm2-snapshot.json
Labels: :white_check_mark: ready

#3226 Genesis Block Schema validation error - Closes #3225
  config/mainnet/genesis_block.json
Labels: :white_check_mark: ready

#3227 Fix undefined logger in Votes logic - Closes #3224
  framework/src/modules/chain/submodules/accounts.js
Labels: :white_check_mark: ready

#3178 Add minimal test coverage config commander - Closes #3175
  framework/src/modules/chain/helpers/config.js
  framework/test/mocha/unit/modules/chain/helpers/config.js
Labels: :white_check_mark: ready

#3223 Remove topAccounts from config file - Closes #2592
  config/default/config.json
  framework/src/modules/chain/schema/config.js
Labels: :white_check_mark: ready
