Repository LiskHQ/lisk-sdk, pull requests merged in 2019-07, with the labels that each got.

#3895 API misreporting the connected peer count and state property is wrong - Closes #3881 #3885 #3907
  elements/lisk-p2p/src/p2p.ts
  elements/lisk-p2p/src/peer_pool.ts
  elements/lisk-p2p/test/unit/peer_pool.ts
  framework/src/modules/chain/submodules/peers.js
  framework/src/modules/http_api/controllers/node.js
  framework/src/modules/network/filter_peers.js
  framework/src/modules/network/index.js
  framework/src/modules/network/network.js
  framework/test/mocha/unit/modules/chain/submodules/peers.js
  framework/test/mocha/unit/modules/http_api/controllers/node.js
Labels: :white_check_mark: ready

#3909 Update broadcastLimit with emitPeerLimit and its values across framework - Closes #3905
  framework/test/jest/unit/specs/controller/__snapshots__/application.spec.js.snap
  framework/test/mocha/unit/modules/chain/logic/broadcaster.js
Labels: :white_check_mark: ready

#3890 Improve create and sign any transaction functionality in Lisk Transactions - Closes #3739
  elements/lisk-transactions/src/base_transaction.ts
  elements/lisk-transactions/test/base_transaction.ts
  framework/src/modules/http_api/controllers/node.js
Labels: :eye: pending review

#3858 Add more propagation tests - Closes #3812
  elements/lisk-p2p/src/p2p_request.ts
  elements/lisk-p2p/test/integration/p2p.ts
Labels: :eye: pending review

#3855 Remove relayLimit from broadcaster - Closes #3819
  framework/src/modules/chain/blocks/process.js
  framework/src/modules/chain/defaults/config.js
  framework/src/modules/chain/logic/broadcaster.js
  framework/src/modules/chain/transport.js
  framework/test/jest/unit/specs/controller/__snapshots__/application.spec.js.snap
  framework/test/mocha/unit/modules/chain/logic/broadcaster.js
  framework/test/mocha/unit/modules/chain/transport.js
  sdk/src/samples/config_devnet.json
Labels: :eye: pending review

#3893 Assign and verify transaction fees in Transactions domain - Closes #3860
  elements/lisk-transactions/src/0_transfer_transaction.ts
  elements/lisk-transactions/src/1_second_signature_transaction.ts
  elements/lisk-transactions/src/2_delegate_transaction.ts
  elements/lisk-transactions/src/3_vote_transaction.ts
  elements/lisk-transactions/src/4_multisignature_transaction.ts
  elements/lisk-transactions/src/5_dapp_transaction.ts
  elements/lisk-transactions/src/base_transaction.ts
  elements/lisk-transactions/src/utils/validation/validation.ts
  elements/lisk-transactions/test/base_transaction.ts
  elements/lisk-transactions/test/helpers/test_transaction_class.ts
  elements/lisk-transactions/test/utils/validation/validation.ts
  elements/lisk-transactions/test/utils/validation/validator.ts
  framework/test/mocha/integration/matcher.js
Labels: :white_check_mark: ready

#3918 Unreacheable peers are kept as connected for too long - Close #3917
  elements/lisk-p2p/src/peer.ts
Labels: :white_check_mark: ready

#3903 Commander does not allow upgrading using a custom build - Closes #3901 #3898 #3911
  commander/src/commands/core/install.ts
  commander/src/commands/core/upgrade.ts
  commander/src/utils/core/commons.ts
  commander/src/utils/core/config.ts
  commander/test/utils/core/commons.ts
  commander/test/utils/core/config.ts
Labels: :white_check_mark: ready

#3921 Improve usability of StateStore to get and set new values for accounts - Closes #3913
  framework/src/modules/chain/logic/state_store/account_store.js
  framework/src/modules/chain/submodules/blocks/chain.js
  framework/test/mocha/integration/state_store/account_store.js
Labels: :white_check_mark: ready

#3853 Automatically cleanup round_delegates table - Closes #3683
  framework/src/modules/chain/bft/bft.js
  framework/src/modules/chain/chain.js
  framework/src/modules/chain/components/storage/entities/round_delegates.js
  framework/src/modules/chain/dpos/delegates.js
  framework/src/modules/chain/dpos/dpos.js
  framework/src/modules/chain/migrations/sql/20190522152200_add_round_delegates_table.sql
  framework/src/modules/chain/migrations/sql/20190524120600_add_default_value_asset_mem_account.sql
  framework/test/mocha/common/application.js
  framework/test/mocha/common/storage_sandbox.js
  framework/test/mocha/integration/dpos/delegate.js
Labels: :white_check_mark: ready

#3920 Commander should remove backup on uninstall - Closes #3919
  commander/src/commands/core/uninstall.ts
  commander/src/commands/core/upgrade.ts
  commander/test/utils/core/commons.ts
Labels: :white_check_mark: ready

#3926 Uncaught TypeError in checkProtocolVersionCompatibility P2P validation method - Closes #3923
  elements/lisk-p2p/src/validation.ts
Labels: :white_check_mark: ready

#3930 Set websocket maxPayload on P2P library - Closes #3335
  elements/lisk-p2p/src/p2p.ts
  elements/lisk-p2p/src/p2p_types.ts
  elements/lisk-p2p/src/peer.ts
  elements/lisk-p2p/src/peer_pool.ts
  elements/lisk-p2p/test/integration/p2p.ts
  elements/lisk-p2p/test/unit/peer_pool.ts
Labels: :white_check_mark: ready

#3927 Missing await for async call - Closes #3922
  framework/src/modules/chain/submodules/blocks/chain.js
Labels: :white_check_mark: ready

#3931 Node fail to sync when block contains multisignature transaction - Closes #3612
  elements/lisk-transactions/src/4_multisignature_transaction.ts
  elements/lisk-transactions/test/4_multisignature_transaction.ts
Labels: :white_check_mark: ready

#3882 Maintain received time of last received applied block - Closes #3557
  framework/src/modules/chain/blocks/blocks.js
  framework/src/modules/chain/blocks/fork_choice_rule.js
  framework/test/jest/unit/specs/modules/chain/blocks/fork_choice_rule.spec.js
  framework/test/mocha/unit/modules/chain/blocks/blocks.js
Labels: :white_check_mark: ready

#3936 Use transaction not transactions in lisk-client readme - Closes #3925
  elements/lisk-client/src/index.ts
  elements/lisk-client/test/index.ts
  elements/lisk-elements/src/index.ts
  elements/lisk-elements/test/index.ts
Labels: :white_check_mark: ready

#3880 Add validation of custom transaction - Closes #3877
  elements/lisk-transactions/src/index.ts
  elements/lisk-transactions/src/utils/validation/index.ts
  elements/lisk-transactions/src/utils/validation/schema.ts
  framework/package-lock.json
  framework/package.json
  framework/src/controller/application.js
  framework/src/controller/validator/index.js
  framework/src/errors.js
  framework/test/jest/unit/specs/controller/__snapshots__/application.spec.js.snap
  framework/test/jest/unit/specs/controller/application.spec.js
  framework/test/jest/unit/specs/controller/helpers/validator/validator.spec.js
Labels: :white_check_mark: ready

#3924 Check the error exists or not and then return with proper message
  framework/src/modules/chain/submodules/loader.js
  framework/test/mocha/unit/modules/chain/submodules/loader.js
Labels: :white_check_mark: ready

#3937 Uncaught TypeError in checkProtocolVersionCompatibility P2P validation method - Closes #3923
  elements/lisk-p2p/test/integration/p2p.ts
Labels: :eye: pending review

#3940 application_config_schema.js not being used and Application/Schema invalid syntax - Closes #3939
  framework/src/controller/schema/application_config_schema.js
  framework/src/controller/schema/genesis_block_schema.js
  framework/test/fixtures/config/devnet/config.json
  framework/test/jest/unit/specs/controller/__snapshots__/application.spec.js.snap
  framework/test/jest/unit/specs/controller/application.spec.js
  framework/test/jest/unit/specs/controller/schema/__snapshots__/application_schema.spec.js.snap
  framework/test/jest/unit/specs/controller/schema/__snapshots__/genesis_block_schema.spec.js.snap
Labels: :white_check_mark: ready

#3945 Custom transaction fails to validate if `FEE` member is not defined - Closes #3941
  elements/lisk-transactions/src/base_transaction.ts
  elements/lisk-transactions/test/base_transaction.ts
  elements/lisk-transactions/test/helpers/index.ts
  elements/lisk-transactions/test/helpers/test_transaction_class.ts
Labels: :white_check_mark: ready

#3932 Transaction pool behavior breaks backward compatibility causing hard-fork - Closes #3914
  elements/lisk-transaction-pool/src/transaction_pool.ts
  elements/lisk-transaction-pool/test/unit/transaction_pool.ts
  framework/src/modules/chain/logic/block.js
  framework/src/modules/chain/logic/state_store/account_store.js
  framework/src/modules/chain/submodules/blocks/chain.js
  framework/src/modules/chain/submodules/blocks/process.js
  framework/src/modules/chain/submodules/process_transactions.js
  framework/test/mocha/common/utils/blocks_and_transactions_helper.js
  framework/test/mocha/integration/blocks/blocks_and_transactions.js
  framework/test/mocha/integration/blocks/verify/verify.js
  framework/test/mocha/integration/common.js
  framework/test/mocha/integration/process_transactions.js
  framework/test/mocha/unit/modules/chain/logic/process_transactions.js
  framework/test/mocha/unit/modules/chain/submodules/blocks/chain.js
  framework/test/mocha/unit/modules/chain/submodules/blocks/process.js
  framework/test/mocha/unit/modules/chain/submodules/process_transactions.js
  framework/test/mocha/unit/modules/chain/submodules/transport.js
Labels: :white_check_mark: ready

#3943 Add registerTransaction to README - Closes #3743
  sdk/README.md
Labels: :white_check_mark: ready

#3946 Prevent crashing the application when a block is received and node is syncing or forging - Closes #3896
  framework/src/modules/chain/chain.js
  framework/test/mocha/unit/modules/chain/chain.js
Labels: :white_check_mark: ready

#3957 Bus sockets timeout - Closes #3942
  framework/src/controller/application.js
  framework/src/controller/controller.js
  framework/src/controller/schema/application_config_schema.js
  framework/src/controller/system_dirs.js
  framework/src/controller/validator/formats.js
  framework/test/jest/unit/specs/controller/__snapshots__/application.spec.js.snap
  framework/test/jest/unit/specs/controller/application.spec.js
  framework/test/jest/unit/specs/controller/controller.spec.js
  framework/test/jest/unit/specs/controller/helpers/system_dirs.spec.js
  framework/test/jest/unit/specs/controller/schema/__snapshots__/application_schema.spec.js.snap
Labels: :white_check_mark: ready

#3938 Remove coverall and use Jenkins - Closes #3322
  Jenkinsfile.sdk
  commander/package-lock.json
  commander/package.json
  elements/lisk-validator/package-lock.json
  framework/Jenkinsfile
  framework/package-lock.json
  framework/package.json
  framework/test/jest/config/jest.config.base.js
  framework/test/jest/unit/specs/jest.config/__snapshots__/jest.config.unit.spec.js.snap
Labels: :white_check_mark: ready

#3950 Add unit tests for __private.undoConfirmedStep and __private.popLastBlock - Closes #3929
  framework/test/mocha/unit/modules/chain/submodules/blocks/chain.js
Labels: :white_check_mark: ready

#3959 Add missing unit tests for transactions processing - Closes #3951
  framework/src/modules/chain/submodules/process_transactions.js
  framework/test/mocha/unit/modules/chain/submodules/process_transactions.js
Labels: :white_check_mark: ready

#3964 Reenable and fix skipped Application unit tests - Closes #3947
  framework/src/controller/application.js
  framework/test/jest/unit/specs/controller/__snapshots__/application.spec.js.snap
  framework/test/jest/unit/specs/controller/application.spec.js
Labels: :white_check_mark: ready

#3974 Node keep disconnecting with peers running older versions - Closes #3961
  elements/lisk-p2p/package.json
  elements/lisk-p2p/src/peer.ts
  framework/package.json
Labels: :white_check_mark: ready

#3960 Isolate next forge next sync concrete impl from task registration logic - Closes #3958
  framework/src/modules/chain/chain.js
  framework/test/mocha/unit/modules/chain/chain.js
Labels: :white_check_mark: ready

#3965 Some transaction events are not being broadcasted - Closes #3962
  framework/src/modules/chain/blocks/blocks.js
  framework/src/modules/chain/chain.js
  framework/src/modules/chain/transaction_pool/index.js
  framework/src/modules/chain/transaction_pool/transaction_pool.js
  framework/src/modules/chain/transport/broadcaster.js
  framework/test/mocha/unit/modules/chain/blocks/blocks.js
  framework/test/mocha/unit/modules/chain/transaction_pool/transaction_pool.js
Labels: :white_check_mark: ready

#3963 Chai-as-promised assertions are giving false positives - Closes #3956
  framework/package.json
  framework/test/mocha/integration/state_store/round_store.js
  framework/test/mocha/unit/components/storage/entities/account.js
  framework/test/mocha/unit/components/storage/entities/block.js
  framework/test/mocha/unit/components/storage/entities/transaction.js
  framework/test/mocha/unit/modules/chain/components/storage/entities/account.js
  framework/test/mocha/unit/modules/chain/components/storage/entities/block.js
  framework/test/mocha/unit/modules/chain/components/storage/entities/round.js
  framework/test/mocha/unit/modules/chain/components/storage/entities/transaction.js
  framework/test/mocha/unit/modules/chain/logic/broadcaster.js
  framework/test/mocha/unit/modules/chain/submodules/blocks/chain.js
  framework/test/mocha/unit/modules/chain/submodules/blocks/verify.js
  framework/test/mocha/unit/modules/http_api/controllers/delegates.js
  framework/test/mocha/unit/modules/network/components/storage/entities/peer.js
Labels: :white_check_mark: ready

#3978 Sequence should not be used in Loader - Closes #3977
  framework/src/modules/chain/loader.js
Labels: :white_check_mark: ready

#3883 Update peer selection method for fetchPeers response - Closes #3333
  elements/lisk-p2p/src/p2p.ts
  elements/lisk-p2p/src/p2p_types.ts
  elements/lisk-p2p/test/integration/p2p.ts
Labels: :white_check_mark: ready

#3991 Merge 2.1.0 branch into 2.2.0
  commander/package-lock.json
  commander/package.json
  elements/README.md
  elements/lisk-client/README.md
  elements/lisk-p2p/src/peer.ts
  elements/lisk-transaction-pool/package-lock.json
  elements/lisk-transaction-pool/package.json
  framework/package.json
  framework/src/modules/chain/transactions/transactions_handlers.js
  framework/test/mocha/unit/modules/chain/transactions/transactions_handlers.js
Labels: :white_check_mark: Ready

#4000 Update package lock file
  commander/package-lock.json
  elements/lisk-api-client/package-lock.json
  elements/lisk-client/package-lock.json
  elements/lisk-constants/package-lock.json
  elements/lisk-cryptography/package-lock.json
  elements/lisk-elements/package-lock.json
  elements/lisk-p2p/package-lock.json
  elements/lisk-passphrase/package-lock.json
  elements/lisk-transaction-pool/package-lock.json
  elements/lisk-transactions/package-lock.json
  elements/lisk-validator/package-lock.json
  framework/package-lock.json
  package-lock.json
Labels: :white_check_mark: ready

#3999 Enforce limits on the size of inbound messages/requests in P2P - Closes #3335
  elements/lisk-p2p/src/peer/base.ts
  elements/lisk-p2p/src/peer/outbound.ts
  elements/lisk-p2p/src/peer_pool.ts
  elements/lisk-p2p/test/integration/p2p.ts
Labels: :eye: pending review

#4007 Update issue and PR templates - Close #3302
  docs/ISSUE_TEMPLATE.md
  docs/ISSUE_TEMPLATE_BUG_REPORT.md
  docs/PULL_REQUEST_TEMPLATE.md
Labels: :white_check_mark: ready

#4013 Delay in syncing with network due to too many failed to load block from network - Closes #3954
  framework/src/modules/chain/loader.js
Labels: status: ready

#3985 Restructure the integration tests for Jest - Closes #3986
  framework/test/jest/integration/specs/modules/chain/app.spec.js
  framework/test/jest/integration/specs/modules/chain/blocks/block_version.spec.js
  framework/test/jest/integration/specs/modules/chain/blocks/blocks/on_receive_block.spec.js
  framework/test/jest/integration/specs/modules/chain/blocks/chain/apply_block.spec.js
  framework/test/jest/integration/specs/modules/chain/blocks/chain/delete_last_block_multiple_transactions.spec.js
  framework/test/jest/integration/specs/modules/chain/blocks/chain/delete_last_block_single_transaction.spec.js
  framework/test/jest/integration/specs/modules/chain/blocks/chain/pop_last_block.spec.js
  framework/test/jest/integration/specs/modules/chain/blocks/util.spec.js
  framework/test/jest/integration/specs/modules/chain/blocks/verify.spec.js
  framework/test/jest/integration/specs/modules/chain/dependencies.spec.js
  framework/test/jest/integration/specs/modules/chain/loader/validate_own_chain/first_round.spec.js
  framework/test/jest/integration/specs/modules/chain/loader/validate_own_chain/full_two_rounds.spec.js
  framework/test/jest/integration/specs/modules/chain/loader/validate_own_chain/more_than_two_rounds.spec.js
  framework/test/jest/integration/specs/modules/chain/loader/validate_own_chain/valid_chain_full_round.spec.js
  framework/test/jest/integration/specs/modules/chain/loader/validate_own_chain/valid_chain_partial_round.spec.js
  framework/test/jest/integration/specs/modules/chain/matcher.spec.js
  framework/test/jest/integration/specs/modules/chain/rebuilding.spec.js
  framework/test/jest/integration/specs/modules/chain/rounds.spec.js
  framework/test/jest/integration/specs/modules/chain/scenarios/address_collision.spec.js
  framework/test/jest/integration/specs/modules/chain/scenarios/duplicate_signatures.spec.js
  framework/test/jest/integration/specs/modules/chain/scenarios/null_byte.spec.js
  framework/test/jest/integration/specs/modules/chain/scenarios/recipient_id_exceeding_uint_64.spec.js
  framework/test/jest/integration/specs/modules/chain/scenarios/recipient_id_leading_zero.spec.js
  framework/test/jest/integration/specs/modules/chain/scenarios/total_spending_check.spec.js
  framework/test/jest/integration/specs/modules/chain/scenarios/votes_collision.spec.js
  framework/test/jest/integration/specs/modules/chain/state_store/account_store.spec.js
  framework/test/jest/integration/specs/modules/chain/state_store/round_store.spec.js
  framework/test/jest/integration/specs/modules/chain/state_store/transaction_store.spec.js
  framework/test/jest/integration/specs/modules/chain/synchronous_tasks.spec.js
  framework/test/jest/integration/specs/modules/chain/transaction_pool/unconfirmed_transactions.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/0_0_transfer.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/1_second_signature/1_1_second_signature.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/1_second_signature/1_1_second_signature_from_pool_peer.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/1_second_signature/1_X_second_signature_unconfirmed.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/1_second_signature/1_X_second_signature_validated.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/2_delegates/1_same_account_same_username.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/2_delegates/2_same_account_different_usernames.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/2_delegates/3_different_accounts_same_username.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/2_delegates/4_different_accounts_different_usernames.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/2_delegates/5_same_account_from_pool_and_peer.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/3_3_votes.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/4_multisignature/4_4_multisignature.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/4_multisignature/4_X_multisignature_edge_cases.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/4_multisignature/4_X_multisignature_unconfirmed.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/4_multisignature/4_X_multisignature_validated.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/4_multisignature/4_multisignature_account.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/5_5_dapps.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/exceptions/duplicate_signatures.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/exceptions/multisignature.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/exceptions/sender_public_key_exception.sepc.js
  framework/test/jest/integration/specs/modules/chain/transactions/exceptions/signatures.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/expire_transactions.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/inert_transactions.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/transactions_handlers.spec.js
Labels: status: pending review

#4010 Snapshotting and syncing fails on 2.2 - Closes #4003
  framework/src/modules/chain/transactions/transactions_handlers.js
  framework/test/mocha/integration/process_transactions.js
Labels: status: pending review

#3900 Implement peer selection algorithm for block sync mechanism - Closes #3767
  framework/src/controller/application_state.js
  framework/src/modules/chain/chain.js
  framework/src/modules/chain/synchronizer/block_synchronization_mechanism.js
  framework/src/modules/chain/synchronizer/index.js
  framework/src/modules/chain/synchronizer/synchronizer.js
  framework/test/jest/unit/specs/controller/application_state.spec.js
  framework/test/jest/unit/specs/modules/chain/synchronizer/block_synchronization_mechanism/block_synchronization_mechanism.spec.js
  framework/test/jest/unit/specs/modules/chain/synchronizer/block_synchronization_mechanism/peers.js
Labels: status: ready

#4014 Fix folder structure for issue template
  docs/ISSUE_TEMPLATE/ISSUE_TEMPLATE_BUG_REPORT.md
  docs/ISSUE_TEMPLATE/ISSUE_TEMPLATE_FEATURE.md
Labels: status: pending review

#4020 Merge development to feature/introduce_bft_consensus branch
  docs/ISSUE_TEMPLATE/ISSUE_TEMPLATE_BUG_REPORT.md
  docs/ISSUE_TEMPLATE/ISSUE_TEMPLATE_FEATURE.md
  docs/PULL_REQUEST_TEMPLATE.md
  framework/src/modules/chain/loader.js
  framework/src/modules/chain/transactions/transactions_handlers.js
  framework/test/jest/integration/specs/modules/chain/app.spec.js
  framework/test/jest/integration/specs/modules/chain/blocks/block_version.spec.js
  framework/test/jest/integration/specs/modules/chain/blocks/blocks/on_receive_block.spec.js
  framework/test/jest/integration/specs/modules/chain/blocks/chain/apply_block.spec.js
  framework/test/jest/integration/specs/modules/chain/blocks/chain/delete_last_block_multiple_transactions.spec.js
  framework/test/jest/integration/specs/modules/chain/blocks/chain/delete_last_block_single_transaction.spec.js
  framework/test/jest/integration/specs/modules/chain/blocks/chain/pop_last_block.spec.js
  framework/test/jest/integration/specs/modules/chain/blocks/util.spec.js
  framework/test/jest/integration/specs/modules/chain/blocks/verify.spec.js
  framework/test/jest/integration/specs/modules/chain/dependencies.spec.js
  framework/test/jest/integration/specs/modules/chain/loader/validate_own_chain/first_round.spec.js
  framework/test/jest/integration/specs/modules/chain/loader/validate_own_chain/full_two_rounds.spec.js
  framework/test/jest/integration/specs/modules/chain/loader/validate_own_chain/more_than_two_rounds.spec.js
  framework/test/jest/integration/specs/modules/chain/loader/validate_own_chain/valid_chain_full_round.spec.js
  framework/test/jest/integration/specs/modules/chain/loader/validate_own_chain/valid_chain_partial_round.spec.js
  framework/test/jest/integration/specs/modules/chain/matcher.spec.js
  framework/test/jest/integration/specs/modules/chain/rebuilding.spec.js
  framework/test/jest/integration/specs/modules/chain/rounds.spec.js
  framework/test/jest/integration/specs/modules/chain/scenarios/address_collision.spec.js
  framework/test/jest/integration/specs/modules/chain/scenarios/duplicate_signatures.spec.js
  framework/test/jest/integration/specs/modules/chain/scenarios/null_byte.spec.js
  framework/test/jest/integration/specs/modules/chain/scenarios/recipient_id_exceeding_uint_64.spec.js
  framework/test/jest/integration/specs/modules/chain/scenarios/recipient_id_leading_zero.spec.js
  framework/test/jest/integration/specs/modules/chain/scenarios/total_spending_check.spec.js
  framework/test/jest/integration/specs/modules/chain/scenarios/votes_collision.spec.js
  framework/test/jest/integration/specs/modules/chain/state_store/account_store.spec.js
  framework/test/jest/integration/specs/modules/chain/state_store/round_store.spec.js
  framework/test/jest/integration/specs/modules/chain/state_store/transaction_store.spec.js
  framework/test/jest/integration/specs/modules/chain/synchronous_tasks.spec.js
  framework/test/jest/integration/specs/modules/chain/transaction_pool/unconfirmed_transactions.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/0_0_transfer.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/1_second_signature/1_1_second_signature.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/1_second_signature/1_1_second_signature_from_pool_peer.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/1_second_signature/1_X_second_signature_unconfirmed.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/1_second_signature/1_X_second_signature_validated.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/2_delegates/1_same_account_same_username.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/2_delegates/2_same_account_different_usernames.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/2_delegates/3_different_accounts_same_username.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/2_delegates/4_different_accounts_different_usernames.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/2_delegates/5_same_account_from_pool_and_peer.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/3_3_votes.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/4_multisignature/4_4_multisignature.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/4_multisignature/4_X_multisignature_edge_cases.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/4_multisignature/4_X_multisignature_unconfirmed.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/4_multisignature/4_X_multisignature_validated.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/4_multisignature/4_multisignature_account.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/5_5_dapps.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/exceptions/duplicate_signatures.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/exceptions/multisignature.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/exceptions/sender_public_key_exception.sepc.js
  framework/test/jest/integration/specs/modules/chain/transactions/exceptions/signatures.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/expire_transactions.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/inert_transactions.spec.js
  framework/test/jest/integration/specs/modules/chain/transactions/transactions_handlers.spec.js
  framework/test/mocha/integration/process_transactions.js
Labels: status: ready

#4021 Update gitter badge link
  sdk/README.md
Labels: status: ready

#4018 Remove stdin and gc - Closes #3839
  framework/src/modules/chain/chain.js
Labels: status: ready

#3968 Implement netgrouping for peer eviction and buckets - Closes #3874
  elements/lisk-p2p/package.json
  elements/lisk-p2p/src/utils.ts
  elements/lisk-p2p/test/unit/utils.ts
Labels: status: pending review

#4029 Fix github issue template
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE_BUG_REPORT.md
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE_FEATURE.md
Labels: status: ready

#4017 Add get minimal peers list data for discovery process - Closes #3948
  elements/lisk-p2p/src/p2p.ts
  elements/lisk-p2p/src/p2p_types.ts
  elements/lisk-p2p/src/peer/base.ts
  elements/lisk-p2p/src/peer/index.ts
  elements/lisk-p2p/src/peer/outbound.ts
  elements/lisk-p2p/src/peer_discovery.ts
  elements/lisk-p2p/src/validation.ts
  elements/lisk-p2p/test/integration/p2p.ts
  elements/lisk-p2p/test/unit/peer_discovery.ts
  elements/lisk-p2p/test/unit/validation.ts
Labels: status: pending review

#3981 Rate limit WebSocket messages - Closes #3975
  elements/lisk-p2p/src/p2p.ts
  elements/lisk-p2p/src/p2p_types.ts
  elements/lisk-p2p/src/peer/base.ts
  elements/lisk-p2p/src/peer/inbound.ts
  elements/lisk-p2p/src/peer/outbound.ts
  elements/lisk-p2p/src/peer_pool.ts
  elements/lisk-p2p/test/integration/p2p.ts
  elements/lisk-p2p/test/unit/peer/base.ts
  elements/lisk-p2p/test/unit/peer/inbound_peer.ts
  elements/lisk-p2p/test/unit/peer/outbound_peer.ts
  elements/lisk-p2p/test/unit/peer_pool.ts
  elements/lisk-p2p/test/utils/peers.ts
Labels: status: pending review
